"""Runtime MCP Server — expose L1 operations as MCP tools.

Connects via stdio transport (launched by MCP client).
No port management needed. No daemon.
"""
import os
import subprocess
import sys
import uuid
from pathlib import Path
from typing import Any

RUNTIME_HOME = Path(os.environ.get("RUNTIME_HOME", Path.home() / "runtime"))
PROJECT_HOME = Path(__file__).parent.parent.parent
SCRIPTS_DIR = PROJECT_HOME / "scripts"

# L0 TaskObject runtime — envelope audit trail
_TASKOBJECT_LOG = RUNTIME_HOME / "taskobject_envelopes.jsonl"


def _record_taskobject_envelope(tool_name: str, params: dict, status: str) -> None:
    """Record a TaskObject envelope to the audit trail (side-effect only, no dispatch).

    This proves the TaskObject pipeline is wired and creates a searchable trail
    of all tool calls. The envelope is logged, not dispatched — actual dispatch
    will be enabled when L3 Entry Bridge routes arrive.
    """
    try:
        envelope = {
            "id": str(uuid.uuid4()),
            "intent": "query",
            "context": {"source": "runtime-mcp", "description": f"Tool call: {tool_name}"},
            "target": {"service": "runtime", "tool": tool_name, "params": params},
            "status": status,
            "callback": {"channel": "stdout", "format": "text"},
            "ttl": 60,
            "priority": 2,
        }
        _TASKOBJECT_LOG.parent.mkdir(parents=True, exist_ok=True)
        with open(_TASKOBJECT_LOG, "a") as f:
            import json
            f.write(json.dumps(envelope) + "\n")
    except Exception:
        pass  # non-blocking — logging failure must not break tool execution


def _run_script(script_name: str, *args: str) -> str:
    script = SCRIPTS_DIR / script_name
    env = os.environ.copy()
    env["RUNTIME_HOME"] = str(RUNTIME_HOME)
    try:
        r = subprocess.run(
            [str(script), *args],
            capture_output=True, text=True, timeout=30, env=env,
        )
        return r.stdout.strip() if r.returncode == 0 else (
            f"❌ Error (exit={r.returncode}): {r.stderr.strip() or r.stdout.strip()}")
    except subprocess.TimeoutExpired:
        return "❌ Timeout (30s)"
    except FileNotFoundError:
        return f"❌ Script not found: {script}"

def _matrix_list() -> str:
    from runtime.matrix import list_services
    services = list_services()
    parts = [f"{'NAME':20s} {'TYPE':12s} {'PORT':6s} {'STATUS':12s}", "-" * 60]
    for s in services:
        port = str(s.port) if s.port else "—"
        parts.append(f"{s.name:20s} {s.type:12s} {port:6s} {s.status:12s}")
    return "\n".join(parts)

def _matrix_get(name: str) -> str:
    from runtime.matrix import get_service, resolve_path
    svc = get_service(name)
    if not svc: return f"❌ Service not found: {name}"
    lines = [f"Name:     {svc.name}", f"Type:     {svc.type}", f"Status:   {svc.status}"]
    if svc.port: lines.append(f"Port:     {svc.port}")
    if svc.launchd_label: lines.append(f"Launchd:  {svc.launchd_label}")
    if svc.health_url: lines.append(f"Health:   {svc.health_url}")
    if svc.docker_container: lines.append(f"Docker:   {svc.docker_container}")
    dp = resolve_path(svc.deploy_path)
    if dp: lines.append(f"Deploy:   {dp}")
    lp = resolve_path(svc.log_path)
    if lp: lines.append(f"Logs:     {lp}")
    return "\n".join(lines)

def _protocol_list() -> str:
    from runtime.protocol import L0_PROTOCOLS
    icons = {"active": "✅", "draft": "📝", "planned": "🔲", "deprecated": "🗄️"}
    parts = [f"{'PROTOCOL':25s} {'VERSION':12s} {'CATEGORY':22s} {'STATUS':10s}", "-" * 75]
    for p in L0_PROTOCOLS:
        icon = icons.get(p.status, "❓")
        parts.append(f"{icon} {p.name:22s} {p.version:12s} {p.category:22s} {p.status:10s}")
    parts.append(f"\nTotal: {len(L0_PROTOCOLS)} protocols")
    return "\n".join(parts)

def _protocol_get(name: str) -> str:
    from runtime.protocol import get_protocol
    p = get_protocol(name)
    if not p: return f"❌ Protocol not found: {name}"
    lines = [f"Protocol:  {p.name} v{p.version}", f"Category:  {p.category}", f"Status:    {p.status}", f"Desc:      {p.description}"]
    if p.spec_url: lines.append(f"Spec:      {p.spec_url}")
    if p.port_range: lines.append(f"Ports:     {p.port_range}")
    lines.append(f"Transport: {', '.join(p.transport)}")
    return "\n".join(lines)


# ─── Tool definitions ────────────────────────────────────────────────────

TOOLS = [
    {
        "name": "runtime_health",
        "description": "Run a full health scan of all services. Returns JSON state generated by ecos-matrix-scheduler.",
        "inputSchema": {"type": "object", "properties": {}},
        "handler": lambda args: (RUNTIME_HOME / "matrix_state.json").read_text() if (RUNTIME_HOME / "matrix_state.json").exists() else "State not found. Is Matrix Scheduler running?",
    },
    {
        "name": "runtime_matrix_list",
        "description": "List all services in the runtime matrix.",
        "inputSchema": {"type": "object", "properties": {}},
        "handler": lambda args: _matrix_list(),
    },
    {
        "name": "runtime_matrix_get",
        "description": "Get detailed info about a specific service.",
        "inputSchema": {
            "type": "object",
            "properties": {"name": {"type": "string", "description": "Service name"}},
            "required": ["name"],
        },
        "handler": lambda args: _matrix_get(args["name"]),
    },
    {
        "name": "runtime_service_ctl",
        "description": "Start, stop, restart, or check status of a service.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "name": {"type": "string", "description": "Service name"},
                "action": {"type": "string", "enum": ["status", "start", "stop", "restart"]},
            },
            "required": ["name", "action"],
        },
        "handler": lambda args: _run_script("service-ctl.sh", args["name"], args["action"]),
    },
    {
        "name": "runtime_protocol_list",
        "description": "List all L0 protocols in the registry.",
        "inputSchema": {"type": "object", "properties": {}},
        "handler": lambda args: _protocol_list(),
    },
    {
        "name": "runtime_protocol_get",
        "description": "Get detailed info about a specific protocol.",
        "inputSchema": {
            "type": "object",
            "properties": {"name": {"type": "string", "description": "Protocol name"}},
            "required": ["name"],
        },
        "handler": lambda args: _protocol_get(args["name"]),
    },
    {
        "name": "runtime_ontology_get",
        "description": "Get the eCOS v5 Meta-Model Ontology (L0 SSOT).",
        "inputSchema": {"type": "object", "properties": {}},
        "handler": lambda args: (PROJECT_HOME / "protocols" / "ecos-ontology.yaml").read_text() if (PROJECT_HOME / "protocols" / "ecos-ontology.yaml").exists() else "Ontology not found",
    },
    # ── Tri-Plane Bus Tools ──
    {
        "name": "plane_list",
        "description": "List all L2 Kernel Tri-Planes (governance/engine/memory) and their capabilities.",
        "inputSchema": {"type": "object", "properties": {}},
        "handler": lambda args: _plane_list(),
    },
    {
        "name": "plane_capabilities",
        "description": "Get detailed capabilities of a specific L2 kernel plane.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "plane": {
                    "type": "string",
                    "enum": ["governance", "engine", "memory"],
                    "description": "Plane name: governance (OMO), engine (kairon), memory (gbrain)",
                }
            },
            "required": ["plane"],
        },
        "handler": lambda args: _plane_capabilities(args["plane"]),
    },
    {
        "name": "kei_list",
        "description": "List all registered KEI extensions and their status.",
        "inputSchema": {"type": "object", "properties": {}},
        "handler": lambda args: _kei_list(),
    },
    {
        "name": "kei_inspect",
        "description": "Inspect a specific KEI extension's manifest and permissions.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "extension_id": {"type": "string", "description": "Extension ID (e.g. ecos.plane.governance)"}
            },
            "required": ["extension_id"],
        },
        "handler": lambda args: _kei_inspect(args["extension_id"]),
    },
    {
        "name": "runtime_stats",
        "description": "Show runtime usage statistics — tool calls per service, uptime, extension count.",
        "inputSchema": {"type": "object", "properties": {}},
        "handler": lambda args: _runtime_stats(),
    },
    {
        "name": "taskobject_submit",
        "description": "Submit a TaskObject v1 envelope for execution. The target tool is resolved and executed.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "payload": {"type": "object", "description": "The TaskObject payload (requires id, intent, target.tool)"}
            },
            "required": ["payload"],
        },
        "handler": lambda args: _taskobject_submit(args["payload"]),
    },
    # ── I0 Fabric Tools ──────────────────────────────────────────────────
    {
        "name": "i0_status",
        "description": "I0 Fabric health overview — total/online/offline services, protocols, events, layer breakdown.",
        "inputSchema": {"type": "object", "properties": {}},
        "handler": lambda args: _i0_status(),
    },
    {
        "name": "i0_services",
        "description": "List all services with live port and health probes — port_listening, health status, PID, layer.",
        "inputSchema": {"type": "object", "properties": {}},
        "handler": lambda args: _i0_services(),
    },
    {
        "name": "i0_events",
        "description": "Fetch recent events from Agora SSE endpoint (http://127.0.0.1:7430/api/events).",
        "inputSchema": {
            "type": "object",
            "properties": {
                "limit": {"type": "integer", "description": "Number of events to return (default: 20)", "default": 20}
            },
        },
        "handler": lambda args: _i0_events(args.get("limit", 20)),
    },
    {
        "name": "i0_protocols",
        "description": "Protocol registry summary — total protocols, by usage, by category, full list from L0-registry.yaml.",
        "inputSchema": {"type": "object", "properties": {}},
        "handler": lambda args: _i0_protocols(),
    },
    {
        "name": "i0_graph",
        "description": "Dependency graph — nodes (services by layer) and edges (depends_on relationships) from matrix.yaml.",
        "inputSchema": {"type": "object", "properties": {}},
        "handler": lambda args: _i0_graph(),
    },
]


_STATS: dict[str, int] = {}  # X3: tool call counters


# ─── I0 Fabric handlers ───────────────────────────────────────────────────

def _i0_status() -> str:
    import json
    from runtime.i0 import i0_status as _i0_status_fn
    try:
        status = _i0_status_fn()
        return json.dumps(status, indent=2, default=str)
    except Exception as e:
        return f"❌ i0_status failed: {e}"


def _i0_services() -> str:
    import json
    from runtime.i0 import i0_services as _i0_services_fn
    try:
        services = _i0_services_fn()
        parts = [f"{'SERVICE':20s} {'TYPE':12s} {'PORT':6s} {'LIVE':6s} {'HEALTH':12s} {'LAYER':6s}", "-" * 65]
        for s in services:
            port = str(s["port"]) if s["port"] else "—"
            live = "✅" if s.get("port_listening") else "⏹️"
            parts.append(f"{s['name']:20s} {s['type']:12s} {port:6s} {live:6s} {s.get('health','?'):12s} {s.get('layer','?'):6s}")
        parts.append(f"\nTotal: {len(services)} services ({sum(1 for s in services if s.get('port_listening'))} online)")
        return "\n".join(parts)
    except Exception as e:
        return f"❌ i0_services failed: {e}"


def _i0_events(limit: int = 20) -> str:
    import json
    from runtime.i0 import i0_events as _i0_events_fn
    try:
        events = _i0_events_fn(limit)
        if not events:
            return "⚠️  No events retrieved. Is Agora running on :7430?"
        parts = [f"{'ID':6s} {'TIME':22s} {'SOURCE':20s} {'TYPE':20s} {'PAYLOAD':40s}", "-" * 110]
        for ev in events:
            eid = str(ev.get("id", ""))[:6]
            ts = str(ev.get("time", ev.get("timestamp", "")))[:22]
            src = str(ev.get("source", ""))[:20]
            etype = str(ev.get("type", ""))[:20]
            payload = str(ev.get("payload", ev.get("data", "")))[:40]
            parts.append(f"{eid:6s} {ts:22s} {src:20s} {etype:20s} {payload:40s}")
        parts.append(f"\nShowing {len(events)} events")
        return "\n".join(parts)
    except Exception as e:
        return f"❌ i0_events failed: {e}"


def _i0_protocols() -> str:
    from runtime.i0 import i0_protocols as _i0_protocols_fn
    try:
        protocols = _i0_protocols_fn()
        lines = [f"Total protocols: {protocols['total']}", ""]
        usage = protocols.get("by_usage", {})
        lines.append("By Usage:")
        for u, cnt in sorted(usage.items()):
            lines.append(f"  {u:12s}: {cnt}")
        lines.append("")
        protos = protocols.get("protocols", [])
        lines.append(f"{'NAME':25s} {'VERSION':10s} {'CATEGORY':22s} {'STATUS':10s} {'USAGE':10s}")
        lines.append("-" * 85)
        for p in protos:
            lines.append(f"{p['name']:25s} {p['version']:10s} {p['category']:22s} {p['status']:10s} {p['usage']:10s}")
        return "\n".join(lines)
    except Exception as e:
        return f"❌ i0_protocols failed: {e}"


def _i0_graph() -> str:
    from runtime.i0 import i0_graph as _i0_graph_fn
    try:
        graph = _i0_graph_fn()
        nodes = graph.get("nodes", [])
        edges = graph.get("edges", [])
        lines = [f"Dependency Graph: {len(nodes)} nodes, {len(edges)} edges", ""]
        by_layer: dict[str, list[str]] = {}
        for n in nodes:
            layer = n.get("layer", "?")
            by_layer.setdefault(layer, []).append(n["name"])
        lines.append("Nodes by Layer:")
        for layer in sorted(by_layer):
            names = ", ".join(by_layer[layer])
            lines.append(f"  {layer}: [{names}]")
        if edges:
            lines.append(f"\nEdges ({len(edges)}):")
            for e in edges:
                lines.append(f"  {e['from']} → {e['to']}  [{e.get('type', 'HARD')}]")
        else:
            lines.append("\nNo dependency edges defined")
        return "\n".join(lines)
    except Exception as e:
        return f"❌ i0_graph failed: {e}"


def _kei_list() -> str:
    import yaml
    reg_file = PROJECT_HOME / "protocols" / "kei-extensions.yaml"
    if not reg_file.exists():
        return "❌ KEI Extension Registry not found"
    data = yaml.safe_load(reg_file.read_text())
    exts = data.get("extensions", [])
    lines = [f"{'ID':40s} {'TYPE':16s} {'STATUS':12s}", "-" * 75]
    for e in exts:
        lines.append(f"{e['id']:40s} {e.get('type','?'):16s} {e.get('status','?'):12s}")
    lines.append(f"\nTotal: {len(exts)} extensions registered")
    return "\n".join(lines)


def _kei_inspect(ext_id: str) -> str:
    import yaml
    reg_file = PROJECT_HOME / "protocols" / "kei-extensions.yaml"
    if not reg_file.exists():
        return "❌ KEI Extension Registry not found"
    data = yaml.safe_load(reg_file.read_text())
    exts = data.get("extensions", [])
    e = next((x for x in exts if x["id"] == ext_id), None)
    if not e:
        return f"❌ Extension not found: {ext_id}"
    lines = [f"ID:          {e['id']}", f"Name:        {e['name']}", f"Version:     {e['version']}",
             f"Type:        {e.get('type','?')}", f"Status:      {e.get('status','?')}",
             f"Entry:       {e.get('entrypoint','?')}", f"Desc:        {e.get('description','')}", ""]
    perms = e.get("permissions", {})
    lines.append(f"Permissions:")
    for k, v in perms.items():
        lines.append(f"  {k}: {v}")
    rules = e.get("kei_rules", {})
    lines.append(f"\nKEI Rules:")
    for k, v in rules.items():
        lines.append(f"  {k}: {v}")
    return "\n".join(lines)


def _runtime_stats() -> str:
    import yaml
    # Extension count
    reg_file = PROJECT_HOME / "protocols" / "kei-extensions.yaml"
    ext_count = len(yaml.safe_load(reg_file.read_text()).get("extensions", [])) if reg_file.exists() else 0
    # Plane count
    plane_file = PROJECT_HOME / "protocols" / "tri-plane-registry.yaml"
    plane_count = len(yaml.safe_load(plane_file.read_text()).get("planes", [])) if plane_file.exists() else 0
    # Protocol count
    proto_file = PROJECT_HOME / "protocols" / "L0-registry.yaml"
    proto_count = len(yaml.safe_load(proto_file.read_text()).get("protocols", [])) if proto_file.exists() else 0
    # Tool count
    tool_count = len(TOOLS)
    lines = [
        "╔════════════════════════════════════════╗",
        "║     eCOS Runtime Usage Statistics      ║",
        "╠════════════════════════════════════════╣",
        f"║  MCP Tools:              {tool_count:3d}           ║",
        f"║  Registered Extensions:  {ext_count:3d}           ║",
        f"║  Kernel Planes:          {plane_count:3d}           ║",
        f"║  L0 Protocols:           {proto_count:3d}           ║",
        "╠════════════════════════════════════════╣",
        "║          Tool Call Costing             ║",
        "╠════════════════════════════════════════╣",
    ]
    if not _STATS:
        lines.append("║  (no tool calls yet)                   ║")
    else:
        for tname, cnt in _STATS.items():
            lines.append(f"║  {tname:24s} {cnt:4d}         ║")
    lines.append("╚════════════════════════════════════════╝")
    return "\n".join(lines)


def _taskobject_submit(payload: dict) -> str:
    import json
    from runtime.taskobject_adapter import _validate_taskobject, _utc_now
    error = _validate_taskobject(payload)
    if error:
        return json.dumps({"status": "error", "error": error, "task_id": payload.get("id", "")})
    
    tool_name = payload["target"]["tool"]
    params = payload["target"].get("params", {})
    
    tool = TOOL_MAP.get(tool_name)
    if not tool:
        return json.dumps({"status": "error", "error": f"Tool not found: {tool_name}", "task_id": payload.get("id", "")})
        
    try:
        _STATS[tool_name] = _STATS.get(tool_name, 0) + 1
        result = tool["handler"](params)
        out = {
            "status": "ok",
            "result": result,
            "task_id": payload.get("id", ""),
            "dispatched_at": _utc_now(),
            "source": payload.get("context", {}).get("source", "unknown")
        }
        return json.dumps(out)
    except Exception as e:
        return json.dumps({"status": "error", "error": str(e), "task_id": payload.get("id", "")})


def _plane_list() -> str:
    import yaml
    registry_file = PROJECT_HOME / "protocols" / "tri-plane-registry.yaml"
    if not registry_file.exists():
        return "❌ Tri-Plane Registry not found"
    data = yaml.safe_load(registry_file.read_text())
    planes = data.get("planes", {})
    lines = [f"{'PLANE':15s} {'STATUS':10s} {'CAPABILITIES':30s}", "-" * 60]
    for name, p in planes.items():
        caps = len(p.get("capabilities", []))
        lines.append(f"{p['name']:15s} {p.get('status', '?'):10s} {caps} capabilities")
    lines.append(f"\nTotal: {len(planes)} planes registered")
    return "\n".join(lines)


def _plane_capabilities(plane_name: str) -> str:
    import yaml
    registry_file = PROJECT_HOME / "protocols" / "tri-plane-registry.yaml"
    if not registry_file.exists():
        return "❌ Tri-Plane Registry not found"
    data = yaml.safe_load(registry_file.read_text())
    planes = data.get("planes", {})
    p = planes.get(plane_name)
    if not p:
        return f"❌ Plane not found: {plane_name}"
    lines = [f"Plane:      {p['name']}", f"Status:     {p.get('status', '?')}",
             f"Runtime:    {p.get('runtime', '?')}", f"Entry:      {p.get('entry', '?')}",
             f"Code:       {p.get('code', '?')}", f"Description: {p.get('description', '')}", ""]
    caps = p.get("capabilities", [])
    lines.append(f"Capabilities ({len(caps)}):")
    for c in caps:
        lines.append(f"  • {c['name']}: {c['description']}")
    return "\n".join(lines)


TOOL_MAP = {t["name"]: t for t in TOOLS}


# ─── MCP Server (raw JSON-RPC over stdio) ────────────────────────────────

def send_response(msg: dict) -> None:
    sys.stdout.write(json.dumps(msg) + "\n")
    sys.stdout.flush()

def handle_request(req: dict) -> dict:
    method = req.get("method", "")
    req_id = req.get("id")
    params = req.get("params", {})

    if method == "tools/list":
        return {
            "jsonrpc": "2.0", "id": req_id,
            "result": {
                "tools": [
                    {"name": t["name"], "description": t["description"],
                     "inputSchema": t["inputSchema"],
                     "callCount": _STATS.get(t["name"], 0)}
                    for t in TOOLS
                ]
            }
        }

    elif method == "tools/call":
        tool_name = params.get("name", "")
        arguments = params.get("arguments", {})
        tool = TOOL_MAP.get(tool_name)
        if not tool:
            return {
                "jsonrpc": "2.0", "id": req_id,
                "error": {"code": -32601, "message": f"Tool not found: {tool_name}"}
            }
        try:
            from runtime.kei_sandbox import record_audit
            record_audit("execute", "ecos.runtime.mcp", "pass", f"Tool called: {tool_name}")
            _STATS[tool_name] = _STATS.get(tool_name, 0) + 1
            result = tool["handler"](arguments)
            _record_taskobject_envelope(tool_name, arguments, "ok")
            return {
                "jsonrpc": "2.0", "id": req_id,
                "result": {"content": [{"type": "text", "text": result}]}
            }
        except Exception as e:
            record_audit("execute", "ecos.runtime.mcp", "fail", f"Tool failed: {tool_name}: {e}")
            _STATS[tool_name] = _STATS.get(tool_name, 0) + 1
            _record_taskobject_envelope(tool_name, arguments, "error")
            return {
                "jsonrpc": "2.0", "id": req_id,
                "error": {"code": -32000, "message": str(e)}
            }

    elif method == "ping":
        return {"jsonrpc": "2.0", "id": req_id, "result": {}}

    elif method == "initialize":
        return {
            "jsonrpc": "2.0", "id": req_id,
            "result": {
                "protocolVersion": "2024-11-05",
                "capabilities": {"tools": {}},
                "serverInfo": {"name": "eCOS Runtime", "version": "0.1.0"}
            }
        }

    elif method == "notifications/initialized":
        return None  # no response for notifications

    else:
        return {
            "jsonrpc": "2.0", "id": req_id,
            "error": {"code": -32601, "message": f"Method not found: {method}"}
        }


import json

def main():
    """Main loop: read JSON-RPC from stdin, write to stdout."""
    # KEI sandbox is auto-enabled via PYTHONSTARTUP — no need to call again
    for line in sys.stdin:
        line = line.strip()
        if not line:
            continue
        try:
            req = json.loads(line)
            resp = handle_request(req)
            if resp is not None:
                send_response(resp)
        except json.JSONDecodeError:
            send_response({
                "jsonrpc": "2.0", "id": None,
                "error": {"code": -32700, "message": "Parse error"}
            })
        except Exception as e:
            send_response({
                "jsonrpc": "2.0", "id": None,
                "error": {"code": -32000, "message": str(e)}
            })

if __name__ == "__main__":
    main()
