"""Runtime MCP Server — expose L1 operations as MCP tools.

Connects via stdio transport (launched by MCP client).
No port management needed. No daemon.
"""
import os
import subprocess
import sys
from pathlib import Path
from typing import Any

RUNTIME_HOME = Path(os.environ.get("RUNTIME_HOME", Path.home() / "runtime"))
PROJECT_HOME = Path(__file__).parent.parent.parent
SCRIPTS_DIR = PROJECT_HOME / "scripts"


def _run_script(script_name: str, *args: str) -> str:
    script = SCRIPTS_DIR / script_name
    env = os.environ.copy()
    env["RUNTIME_HOME"] = str(RUNTIME_HOME)
    try:
        r = subprocess.run(
            [str(script), *args],
            capture_output=True, text=True, timeout=30, env=env,
        )
        return r.stdout.strip() if r.returncode == 0 else (
            f"❌ Error (exit={r.returncode}): {r.stderr.strip() or r.stdout.strip()}")
    except subprocess.TimeoutExpired:
        return "❌ Timeout (30s)"
    except FileNotFoundError:
        return f"❌ Script not found: {script}"

def _matrix_list() -> str:
    from runtime.matrix import list_services
    services = list_services()
    parts = [f"{'NAME':20s} {'TYPE':12s} {'PORT':6s} {'STATUS':12s}", "-" * 60]
    for s in services:
        port = str(s.port) if s.port else "—"
        parts.append(f"{s.name:20s} {s.type:12s} {port:6s} {s.status:12s}")
    return "\n".join(parts)

def _matrix_get(name: str) -> str:
    from runtime.matrix import get_service, resolve_path
    svc = get_service(name)
    if not svc: return f"❌ Service not found: {name}"
    lines = [f"Name:     {svc.name}", f"Type:     {svc.type}", f"Status:   {svc.status}"]
    if svc.port: lines.append(f"Port:     {svc.port}")
    if svc.launchd_label: lines.append(f"Launchd:  {svc.launchd_label}")
    if svc.health_url: lines.append(f"Health:   {svc.health_url}")
    if svc.docker_container: lines.append(f"Docker:   {svc.docker_container}")
    dp = resolve_path(svc.deploy_path)
    if dp: lines.append(f"Deploy:   {dp}")
    lp = resolve_path(svc.log_path)
    if lp: lines.append(f"Logs:     {lp}")
    return "\n".join(lines)

def _protocol_list() -> str:
    from runtime.protocol import L0_PROTOCOLS
    icons = {"active": "✅", "draft": "📝", "planned": "🔲", "deprecated": "🗄️"}
    parts = [f"{'PROTOCOL':25s} {'VERSION':12s} {'CATEGORY':22s} {'STATUS':10s}", "-" * 75]
    for p in L0_PROTOCOLS:
        icon = icons.get(p.status, "❓")
        parts.append(f"{icon} {p.name:22s} {p.version:12s} {p.category:22s} {p.status:10s}")
    parts.append(f"\nTotal: {len(L0_PROTOCOLS)} protocols")
    return "\n".join(parts)

def _protocol_get(name: str) -> str:
    from runtime.protocol import get_protocol
    p = get_protocol(name)
    if not p: return f"❌ Protocol not found: {name}"
    lines = [f"Protocol:  {p.name} v{p.version}", f"Category:  {p.category}", f"Status:    {p.status}", f"Desc:      {p.description}"]
    if p.spec_url: lines.append(f"Spec:      {p.spec_url}")
    if p.port_range: lines.append(f"Ports:     {p.port_range}")
    lines.append(f"Transport: {', '.join(p.transport)}")
    return "\n".join(lines)


# ─── Tool definitions ────────────────────────────────────────────────────

TOOLS = [
    {
        "name": "runtime_health",
        "description": "Run a full health scan of all services. Returns JSON state generated by ecos-matrix-scheduler.",
        "inputSchema": {"type": "object", "properties": {}},
        "handler": lambda args: (RUNTIME_HOME / "matrix_state.json").read_text() if (RUNTIME_HOME / "matrix_state.json").exists() else "❌ State not found. Is Matrix Scheduler running?",
    },
    {
        "name": "runtime_matrix_list",
        "description": "List all services in the runtime matrix.",
        "inputSchema": {"type": "object", "properties": {}},
        "handler": lambda args: _matrix_list(),
    },
    {
        "name": "runtime_matrix_get",
        "description": "Get detailed info about a specific service.",
        "inputSchema": {
            "type": "object",
            "properties": {"name": {"type": "string", "description": "Service name"}},
            "required": ["name"],
        },
        "handler": lambda args: _matrix_get(args["name"]),
    },
    {
        "name": "runtime_service_ctl",
        "description": "Start, stop, restart, or check status of a service.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "name": {"type": "string", "description": "Service name"},
                "action": {"type": "string", "enum": ["status", "start", "stop", "restart"]},
            },
            "required": ["name", "action"],
        },
        "handler": lambda args: _run_script("service-ctl.sh", args["name"], args["action"]),
    },
    {
        "name": "runtime_protocol_list",
        "description": "List all L0 protocols in the registry.",
        "inputSchema": {"type": "object", "properties": {}},
        "handler": lambda args: _protocol_list(),
    },
    {
        "name": "runtime_protocol_get",
        "description": "Get detailed info about a specific protocol.",
        "inputSchema": {
            "type": "object",
            "properties": {"name": {"type": "string", "description": "Protocol name"}},
            "required": ["name"],
        },
        "handler": lambda args: _protocol_get(args["name"]),
    },
    {
        "name": "runtime_ontology_get",
        "description": "Get the eCOS v5 Meta-Model Ontology (L0 SSOT).",
        "inputSchema": {"type": "object", "properties": {}},
        "handler": lambda args: (PROJECT_HOME / "protocols" / "ecos-ontology.yaml").read_text() if (PROJECT_HOME / "protocols" / "ecos-ontology.yaml").exists() else "❌ Ontology not found",
    },
    {
        "name": "plane_list",
        "description": "List all L2 Kernel Tri-Planes (governance/engine/memory) and their capabilities.",
        "inputSchema": {"type": "object", "properties": {}},
        "handler": lambda args: _plane_list(),
    },
    {
        "name": "plane_capabilities",
        "description": "Get detailed capabilities of a specific L2 kernel plane.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "plane": {
                    "type": "string",
                    "enum": ["governance", "engine", "memory"],
                    "description": "Plane name: governance (OMO), engine (kairon), memory (gbrain)",
                }
            },
            "required": ["plane"],
        },
        "handler": lambda args: _plane_capabilities(args["plane"]),
    },
    {
        "name": "kei_list",
        "description": "List all registered KEI extensions and their status.",
        "inputSchema": {"type": "object", "properties": {}},
        "handler": lambda args: _kei_list(),
    },
    {
        "name": "kei_inspect",
        "description": "Inspect a specific KEI extension's manifest and permissions.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "extension_id": {"type": "string", "description": "Extension ID (e.g. ecos.plane.governance)"}
            },
            "required": ["extension_id"],
        },
        "handler": lambda args: _kei_inspect(args["extension_id"]),
    },
    {
        "name": "runtime_stats",
        "description": "Show runtime usage statistics — tool calls per service, uptime, extension count.",
        "inputSchema": {"type": "object", "properties": {}},
        "handler": lambda args: _runtime_stats(),
    },
]


_STATS: dict[str, int] = {}  # X3: tool call counters


def _kei_list() -> str:
    import yaml
    reg_file = PROJECT_HOME / "protocols" / "kei-extensions.yaml"
    if not reg_file.exists():
        return "❌ KEI Extension Registry not found"
    data = yaml.safe_load(reg_file.read_text())
    exts = data.get("extensions", [])
    lines = [f"{'ID':40s} {'TYPE':16s} {'STATUS':12s}", "-" * 75]
    for e in exts:
        lines.append(f"{e['id']:40s} {e.get('type','?'):16s} {e.get('status','?'):12s}")
    lines.append(f"\nTotal: {len(exts)} extensions registered")
    return "\n".join(lines)


def _kei_inspect(ext_id: str) -> str:
    import yaml
    reg_file = PROJECT_HOME / "protocols" / "kei-extensions.yaml"
    if not reg_file.exists():
        return "❌ KEI Extension Registry not found"
    data = yaml.safe_load(reg_file.read_text())
    exts = data.get("extensions", [])
    e = next((x for x in exts if x["id"] == ext_id), None)
    if not e:
        return f"❌ Extension not found: {ext_id}"
    lines = [f"ID:          {e['id']}", f"Name:        {e['name']}", f"Version:     {e['version']}",
             f"Type:        {e.get('type','?')}", f"Status:      {e.get('status','?')}",
             f"Entry:       {e.get('entrypoint','?')}", f"Desc:        {e.get('description','')}", ""]
    perms = e.get("permissions", {})
    lines.append(f"Permissions:")
    for k, v in perms.items():
        lines.append(f"  {k}: {v}")
    rules = e.get("kei_rules", {})
    lines.append(f"\nKEI Rules:")
    for k, v in rules.items():
        lines.append(f"  {k}: {v}")
    return "\n".join(lines)


def _runtime_stats() -> str:
    import yaml
    # Extension count
    reg_file = PROJECT_HOME / "protocols" / "kei-extensions.yaml"
    ext_count = len(yaml.safe_load(reg_file.read_text()).get("extensions", [])) if reg_file.exists() else 0
    # Plane count
    plane_file = PROJECT_HOME / "protocols" / "tri-plane-registry.yaml"
    plane_count = len(yaml.safe_load(plane_file.read_text()).get("planes", [])) if plane_file.exists() else 0
    # Protocol count
    proto_file = PROJECT_HOME / "protocols" / "L0-registry.yaml"
    proto_count = len(yaml.safe_load(proto_file.read_text()).get("protocols", [])) if proto_file.exists() else 0
    # Tool count
    tool_count = len(TOOLS)
    lines = [
        "╔════════════════════════════════════════╗",
        "║     eCOS Runtime Usage Statistics      ║",
        "╠════════════════════════════════════════╣",
        f"║  MCP Tools:              {tool_count:3d}        ║",
        f"║  Registered Extensions:  {ext_count:3d}        ║",
        f"║  Kernel Planes:          {plane_count:3d}        ║",
        f"║  L0 Protocols:           {proto_count:3d}        ║",
        "╚════════════════════════════════════════╝",
    ]
    return "\n".join(lines)


def _plane_list() -> str:
    import yaml
    registry_file = PROJECT_HOME / "protocols" / "tri-plane-registry.yaml"
    if not registry_file.exists():
        return "❌ Tri-Plane Registry not found"
    data = yaml.safe_load(registry_file.read_text())
    planes = data.get("planes", {})
    lines = [f"{'PLANE':15s} {'STATUS':10s} {'CAPABILITIES':30s}", "-" * 60]
    for name, p in planes.items():
        caps = len(p.get("capabilities", []))
        lines.append(f"{p['name']:15s} {p.get('status', '?'):10s} {caps} capabilities")
    lines.append(f"\nTotal: {len(planes)} planes registered")
    return "\n".join(lines)


def _plane_capabilities(plane_name: str) -> str:
    import yaml
    registry_file = PROJECT_HOME / "protocols" / "tri-plane-registry.yaml"
    if not registry_file.exists():
        return "❌ Tri-Plane Registry not found"
    data = yaml.safe_load(registry_file.read_text())
    planes = data.get("planes", {})
    p = planes.get(plane_name)
    if not p:
        return f"❌ Plane not found: {plane_name}"
    lines = [f"Plane:      {p['name']}", f"Status:     {p.get('status', '?')}",
             f"Runtime:    {p.get('runtime', '?')}", f"Entry:      {p.get('entry', '?')}",
             f"Code:       {p.get('code', '?')}", f"Description: {p.get('description', '')}", ""]
    caps = p.get("capabilities", [])
    lines.append(f"Capabilities ({len(caps)}):")
    for c in caps:
        lines.append(f"  • {c['name']}: {c['description']}")
    return "\n".join(lines)


TOOL_MAP = {t["name"]: t for t in TOOLS}


# ─── MCP Server (raw JSON-RPC over stdio) ────────────────────────────────

def send_response(msg: dict) -> None:
    sys.stdout.write(json.dumps(msg) + "\n")
    sys.stdout.flush()

def handle_request(req: dict) -> dict:
    method = req.get("method", "")
    req_id = req.get("id")
    params = req.get("params", {})

    if method == "tools/list":
        return {
            "jsonrpc": "2.0", "id": req_id,
            "result": {
                "tools": [
                    {"name": t["name"], "description": t["description"],
                     "inputSchema": t["inputSchema"]}
                    for t in TOOLS
                ]
            }
        }

    elif method == "tools/call":
        tool_name = params.get("name", "")
        arguments = params.get("arguments", {})
        tool = TOOL_MAP.get(tool_name)
        if not tool:
            return {
                "jsonrpc": "2.0", "id": req_id,
                "error": {"code": -32601, "message": f"Tool not found: {tool_name}"}
            }
        try:
            result = tool["handler"](arguments)
            return {
                "jsonrpc": "2.0", "id": req_id,
                "result": {"content": [{"type": "text", "text": result}]}
            }
        except Exception as e:
            return {
                "jsonrpc": "2.0", "id": req_id,
                "error": {"code": -32000, "message": str(e)}
            }

    elif method == "ping":
        return {"jsonrpc": "2.0", "id": req_id, "result": {}}

    elif method == "initialize":
        return {
            "jsonrpc": "2.0", "id": req_id,
            "result": {
                "protocolVersion": "2024-11-05",
                "capabilities": {"tools": {}},
                "serverInfo": {"name": "eCOS Runtime", "version": "0.1.0"}
            }
        }

    elif method == "notifications/initialized":
        return None  # no response for notifications

    else:
        return {
            "jsonrpc": "2.0", "id": req_id,
            "error": {"code": -32601, "message": f"Method not found: {method}"}
        }


import json

def main():
    """Main loop: read JSON-RPC from stdin, write to stdout."""
    for line in sys.stdin:
        line = line.strip()
        if not line:
            continue
        try:
            req = json.loads(line)
            resp = handle_request(req)
            if resp is not None:
                send_response(resp)
        except json.JSONDecodeError:
            send_response({
                "jsonrpc": "2.0", "id": None,
                "error": {"code": -32700, "message": "Parse error"}
            })
        except Exception as e:
            send_response({
                "jsonrpc": "2.0", "id": None,
                "error": {"code": -32000, "message": str(e)}
            })

if __name__ == "__main__":
    main()
