"""Cockpit page catalog — COCKPIT_PAGES and related mappings.

Split from api_system_map_catalog.py (god-module SRP, T6-10).
Pure data, no logic dependencies.
"""

from __future__ import annotations

from typing import Any

COCKPIT_PAGES: tuple[dict[str, Any], ...] = (
    {
        "id": "Home",
        "title": "首页",
        "group": "入口",
        "purpose": "健康、告警、任务、指标趋势的日常总览。",
        "dimensions": ("entry", "governance", "runtime"),
    },
    {
        "id": "Guide",
        "title": "站内导览",
        "group": "入口",
        "purpose": "把页面、工作带和推荐入口梳成上手总览。",
        "dimensions": ("entry", "orientation", "coverage"),
    },
    {
        "id": "SystemMap",
        "title": "系统地图",
        "group": "入口",
        "purpose": "按层级、项目、能力域和使用路径解释整个 Cockpit。",
        "dimensions": ("entry", "architecture", "coverage"),
    },
    {
        "id": "DomainApps",
        "title": "应用中心",
        "group": "领域应用",
        "purpose": "挂载家庭驾驶舱、OPC 作战台和领域服务。",
        "dimensions": ("domain", "l4", "entry"),
    },
    {
        "id": "Overview",
        "title": "概览中心",
        "group": "运行大盘",
        "purpose": "查看服务节点、运行状态和集群概貌。",
        "dimensions": ("runtime", "service", "health"),
    },
    {
        "id": "McpMesh",
        "title": "网格与 MCP",
        "group": "运行大盘",
        "purpose": "调试 MCP 实例、BOS URI 和路由解析。",
        "dimensions": ("routing", "mcp", "bos"),
    },
    {
        "id": "Topology",
        "title": "全局拓扑",
        "group": "运行大盘",
        "purpose": "观察服务关系、调用流和拓扑健康。",
        "dimensions": ("routing", "runtime", "service"),
    },
    {
        "id": "Compute",
        "title": "算力调配",
        "group": "运行大盘",
        "purpose": "查看模型网关、节点、成本和算力路由。",
        "dimensions": ("compute", "runtime", "cost"),
    },
    {
        "id": "Research",
        "title": "研究中枢",
        "group": "智能与知识",
        "purpose": "管理研究对象、来源、追问、时间线和发布承接。",
        "dimensions": ("research", "knowledge", "publishing"),
    },
    {
        "id": "Protocol",
        "title": "协议工作台",
        "group": "智能与知识",
        "purpose": "巡检工作流定义、动作、后端和协议层运行证据。",
        "dimensions": ("protocol", "workflow", "lifecycle"),
    },
    {
        "id": "Knowledge",
        "title": "知识中枢",
        "group": "智能与知识",
        "purpose": "进入 GBrain/KOS 类知识检索与记忆面。",
        "dimensions": ("knowledge", "memory", "reasoning"),
    },
    {
        "id": "GBrainAdmin",
        "title": "GBrain 管理",
        "group": "智能与知识",
        "purpose": "管理智能体接入、访问凭证、模型校准与请求审计。",
        "dimensions": ("agent", "credentials", "calibration", "audit"),
    },
    {
        "id": "Engines",
        "title": "引擎调度",
        "group": "智能与知识",
        "purpose": "管理 Kairon、GBrain 等引擎状态。",
        "dimensions": ("engine", "knowledge", "runtime"),
    },
    {
        "id": "Assets",
        "title": "技术资产库",
        "group": "智能与知识",
        "purpose": "索引技能、工具管线和自动化工作流。",
        "dimensions": ("capability", "workflow", "tooling"),
    },
    {
        "id": "Workflows",
        "title": "MetaOS 工作流",
        "group": "智能与知识",
        "purpose": "跟踪和测试 Agent 工作流编排。",
        "dimensions": ("orchestration", "workflow", "agent"),
    },
    {
        "id": "C2G",
        "title": "C2G 战略中心",
        "group": "系统治理",
        "purpose": "把战略意图、任务和治理卡片串起来。",
        "dimensions": ("strategy", "governance", "task"),
    },
    {
        "id": "AlertCenter",
        "title": "告警中心",
        "group": "系统治理",
        "purpose": "统一查看告警、规则和处置状态。",
        "dimensions": ("governance", "alert", "health"),
    },
    {
        "id": "L4Health",
        "title": "L4 域健康",
        "group": "系统治理",
        "purpose": "观察自我层域健康、趋势和风险。",
        "dimensions": ("l4", "domain", "health"),
    },
    {
        "id": "Debt",
        "title": "技术债务",
        "group": "系统治理",
        "purpose": "查看技术债、评分和风险闭环。",
        "dimensions": ("governance", "debt", "quality"),
    },
    {
        "id": "Observability",
        "title": "运行可观测",
        "group": "系统治理",
        "purpose": "聚合日志、指标和链路观测入口。",
        "dimensions": ("observability", "runtime", "health"),
    },
    {
        "id": "LogViewer",
        "title": "日志查看器",
        "group": "开发工具",
        "purpose": "检索运行日志和问题现场。",
        "dimensions": ("debug", "runtime", "logs"),
    },
    {
        "id": "TaskCenter",
        "title": "任务中心",
        "group": "开发工具",
        "purpose": "统一查看任务状态、进度和操作控制。",
        "dimensions": ("task", "governance", "workflow"),
    },
    {
        "id": "Performance",
        "title": "性能监控",
        "group": "开发工具",
        "purpose": "查看 CPU、内存、磁盘、网络指标。",
        "dimensions": ("performance", "runtime", "health"),
    },
    {
        "id": "Sandbox",
        "title": "隔离沙箱",
        "group": "开发工具",
        "purpose": "在隔离环境中执行测试或未校验命令。",
        "dimensions": ("runtime", "sandbox", "execution"),
    },
    {
        "id": "QuestBoard",
        "title": "积分冒险",
        "group": "领域应用",
        "purpose": "承接家庭任务、奖励和游戏化体验。",
        "dimensions": ("family", "domain", "motivation"),
    },
    {
        "id": "Settings",
        "title": "底层设置",
        "group": "系统配置",
        "purpose": "配置路由、令牌和治理阈值。",
        "dimensions": ("config", "governance", "runtime"),
    },
)

# 页面自身的低风险操作。项目动作另由项目矩阵提供，成熟度计算需要把两类证据合并。
PAGE_OPERATOR_ACTIONS: dict[str, tuple[str, ...]] = {
    "Home": ("refresh-home", "open-system-map", "open-task-center"),
    "Guide": ("open-guide-group", "open-system-map", "open-task-center"),
    "DomainApps": ("open-app", "open-api", "copy-start", "copy-verify"),
    "Overview": ("refresh-runtime", "open-system-map"),
    "McpMesh": ("refresh-mesh", "copy-bos-uri", "open-service"),
    "Topology": ("refresh-topology", "inspect-node"),
    "Compute": ("refresh-compute", "copy-route", "open-cost-board"),
    "Research": ("copy-research-command", "open-research-detail", "open-task-center"),
    "Knowledge": ("search-knowledge", "write-knowledge", "open-source"),
    "GBrainAdmin": ("refresh-gbrain", "manage-agents", "manage-credentials", "open-request-log"),
    "Engines": ("refresh-engines", "open-engine"),
    "Assets": ("search-assets", "open-asset", "copy-command"),
    "Protocol": ("refresh-protocol", "open-workflow", "copy-validation"),
    "Workflows": ("refresh-workflows", "approve-workflow", "open-run"),
    "C2G": ("approve-proposal", "reject-proposal", "fix-drift"),
    "AlertCenter": ("acknowledge-alert", "silence-alert", "resolve-alert", "manage-rules"),
    "L4Health": ("refresh-l4-health", "open-domain"),
    "Debt": ("refresh-debt", "open-debt-source"),
    "Observability": ("refresh-observability", "open-log-context"),
    "LogViewer": ("refresh-logs", "filter-logs", "open-log-source"),
    "TaskCenter": (
        "request-task-approval",
        "approve-task",
        "pause-task",
        "resume-task",
        "dispatch-task",
        "record-execution-evidence",
        "complete-task",
        "open-task-source",
    ),
    "Performance": ("refresh-performance", "select-time-range"),
    "Sandbox": ("execute-sandbox", "copy-sandbox-code", "open-execution-log"),
    "QuestBoard": ("create-quest", "complete-quest", "refresh-quests"),
    "Settings": ("register-instance", "copy-endpoint", "open-mesh"),
}

# Keep the human-facing contract next to the stable action IDs.  The IDs are
# useful for APIs and task de-duplication; the rest of the site should not
# force operators to decode implementation names such as ``refresh-home``.
PAGE_OPERATOR_ACTION_METADATA: dict[str, dict[str, str]] = {
    "refresh-home": {
        "label": "刷新首页证据",
        "kind": "navigate",
        "risk": "low",
        "description": "回到首页重新读取健康、告警和任务摘要。",
    },
    "open-system-map": {
        "label": "打开系统地图",
        "kind": "navigate",
        "risk": "low",
        "description": "在系统地图查看页面、项目和能力关联。",
    },
    "open-task-center": {
        "label": "打开任务中心",
        "kind": "navigate",
        "risk": "low",
        "description": "进入任务中心查看待处理和已承接事项。",
    },
    "open-guide-group": {
        "label": "打开工作带导览",
        "kind": "navigate",
        "risk": "low",
        "description": "回到站内导览选择当前场景的使用路径。",
    },
    "open-app": {
        "label": "打开领域应用",
        "kind": "navigate",
        "risk": "low",
        "description": "进入应用中心查看领域应用入口和运行状态。",
    },
    "open-api": {
        "label": "查看应用接口",
        "kind": "navigate",
        "risk": "low",
        "description": "查看领域应用的 API 挂载与访问信息。",
    },
    "copy-start": {
        "label": "复制启动命令",
        "kind": "navigate",
        "risk": "low",
        "description": "进入应用中心复制启动命令，不在 Cockpit 内直接执行。",
    },
    "copy-verify": {
        "label": "复制验证命令",
        "kind": "navigate",
        "risk": "low",
        "description": "进入应用中心复制验证命令并保留人工确认边界。",
    },
    "refresh-runtime": {
        "label": "刷新运行状态",
        "kind": "navigate",
        "risk": "low",
        "description": "回到概览中心重新探测服务和端口状态。",
    },
    "refresh-mesh": {
        "label": "刷新网格状态",
        "kind": "navigate",
        "risk": "low",
        "description": "重新读取 MCP、BOS URI 和路由解析状态。",
    },
    "copy-bos-uri": {
        "label": "复制 BOS 地址",
        "kind": "navigate",
        "risk": "low",
        "description": "进入网格页面复制权威 BOS URI。",
    },
    "open-service": {
        "label": "打开服务详情",
        "kind": "navigate",
        "risk": "low",
        "description": "在网格页面查看服务节点和路由信息。",
    },
    "refresh-topology": {
        "label": "刷新拓扑",
        "kind": "navigate",
        "risk": "low",
        "description": "重新读取服务关系、调用流和拓扑健康。",
    },
    "inspect-node": {
        "label": "检查节点",
        "kind": "navigate",
        "risk": "low",
        "description": "进入拓扑页面定位具体服务节点。",
    },
    "refresh-compute": {
        "label": "刷新算力状态",
        "kind": "navigate",
        "risk": "low",
        "description": "重新读取节点、模型路由和成本状态。",
    },
    "copy-route": {
        "label": "复制算力路由",
        "kind": "navigate",
        "risk": "low",
        "description": "进入算力页面查看并复制当前路由信息。",
    },
    "open-cost-board": {
        "label": "查看成本面板",
        "kind": "navigate",
        "risk": "low",
        "description": "进入算力页面查看成本与资源消耗。",
    },
    "copy-research-command": {
        "label": "复制研究命令",
        "kind": "navigate",
        "risk": "low",
        "description": "进入研究中枢复制可复用的研究入口命令。",
    },
    "open-research-detail": {
        "label": "打开研究详情",
        "kind": "navigate",
        "risk": "low",
        "description": "进入研究中枢定位研究对象和时间线。",
    },
    "search-knowledge": {
        "label": "检索知识",
        "kind": "navigate",
        "risk": "low",
        "description": "进入知识中枢发起检索并查看来源。",
    },
    "write-knowledge": {
        "label": "写入知识",
        "kind": "queue",
        "risk": "medium",
        "description": "把知识写入动作带入任务中心，补齐来源和证据后再执行。",
    },
    "open-source": {
        "label": "打开来源",
        "kind": "navigate",
        "risk": "low",
        "description": "进入知识页面查看来源和证据上下文。",
    },
    "refresh-gbrain": {
        "label": "刷新 GBrain 状态",
        "kind": "navigate",
        "risk": "low",
        "description": "重新读取智能体、凭证和请求审计状态。",
    },
    "manage-agents": {
        "label": "管理智能体",
        "kind": "queue",
        "risk": "medium",
        "description": "进入任务中心承接智能体配置变更。",
    },
    "manage-credentials": {
        "label": "管理访问凭证",
        "kind": "queue",
        "risk": "high",
        "description": "进入受控任务流程处理凭证变更。",
    },
    "open-request-log": {
        "label": "打开请求日志",
        "kind": "navigate",
        "risk": "low",
        "description": "进入 GBrain 管理页查看请求审计。",
    },
    "refresh-engines": {
        "label": "刷新引擎状态",
        "kind": "navigate",
        "risk": "low",
        "description": "重新读取引擎和模型供给状态。",
    },
    "open-engine": {
        "label": "打开引擎详情",
        "kind": "navigate",
        "risk": "low",
        "description": "进入引擎调度页定位具体引擎。",
    },
    "search-assets": {
        "label": "检索技术资产",
        "kind": "navigate",
        "risk": "low",
        "description": "进入技术资产库查找可复用技能和工具。",
    },
    "open-asset": {
        "label": "打开资产详情",
        "kind": "navigate",
        "risk": "low",
        "description": "进入技术资产库查看资产详情。",
    },
    "copy-command": {
        "label": "复制资产命令",
        "kind": "navigate",
        "risk": "low",
        "description": "进入资产库复制命令并保留人工执行确认。",
    },
    "refresh-protocol": {
        "label": "刷新协议状态",
        "kind": "navigate",
        "risk": "low",
        "description": "重新读取协议、动作和后端证据。",
    },
    "open-workflow": {
        "label": "打开工作流",
        "kind": "navigate",
        "risk": "low",
        "description": "进入工作流页面查看运行链路。",
    },
    "copy-validation": {
        "label": "复制验证命令",
        "kind": "navigate",
        "risk": "low",
        "description": "进入协议页面复制验证命令。",
    },
    "refresh-workflows": {
        "label": "刷新工作流",
        "kind": "navigate",
        "risk": "low",
        "description": "重新读取 Agent 工作流运行和验证状态。",
    },
    "approve-workflow": {
        "label": "审批工作流",
        "kind": "queue",
        "risk": "medium",
        "description": "把审批动作带入任务中心，补齐审批依据后执行。",
    },
    "open-run": {
        "label": "打开运行记录",
        "kind": "navigate",
        "risk": "low",
        "description": "进入工作流页面查看运行详情和证据。",
    },
    "approve-proposal": {
        "label": "审批治理提案",
        "kind": "queue",
        "risk": "high",
        "description": "进入受控任务流程审批提案。",
    },
    "reject-proposal": {
        "label": "驳回治理提案",
        "kind": "queue",
        "risk": "high",
        "description": "进入受控任务流程驳回提案并记录理由。",
    },
    "fix-drift": {
        "label": "承接漂移修复",
        "kind": "queue",
        "risk": "medium",
        "description": "把治理漂移修复登记为任务并补验证证据。",
    },
    "acknowledge-alert": {
        "label": "确认告警",
        "kind": "queue",
        "risk": "medium",
        "description": "进入告警处置流程确认告警。",
    },
    "silence-alert": {
        "label": "静默告警",
        "kind": "queue",
        "risk": "high",
        "description": "进入受控流程设置静默窗口并记录理由。",
    },
    "resolve-alert": {
        "label": "解决告警",
        "kind": "queue",
        "risk": "medium",
        "description": "进入告警处置流程补充解决证据。",
    },
    "manage-rules": {
        "label": "管理告警规则",
        "kind": "queue",
        "risk": "high",
        "description": "进入受控任务流程修改告警规则。",
    },
    "refresh-l4-health": {
        "label": "刷新域健康",
        "kind": "navigate",
        "risk": "low",
        "description": "重新读取 L4 域健康、风险和趋势。",
    },
    "open-domain": {
        "label": "打开领域详情",
        "kind": "navigate",
        "risk": "low",
        "description": "进入 L4 健康页面定位具体领域。",
    },
    "refresh-debt": {
        "label": "刷新技术债",
        "kind": "navigate",
        "risk": "low",
        "description": "重新读取技术债账本和治理优先级。",
    },
    "open-debt-source": {
        "label": "打开债务来源",
        "kind": "navigate",
        "risk": "low",
        "description": "进入技术债页面查看来源和关闭证据。",
    },
    "refresh-observability": {
        "label": "刷新可观测证据",
        "kind": "navigate",
        "risk": "low",
        "description": "重新读取指标、日志和链路证据。",
    },
    "open-log-context": {
        "label": "打开日志上下文",
        "kind": "navigate",
        "risk": "low",
        "description": "进入日志页面查看异常现场。",
    },
    "refresh-logs": {
        "label": "刷新日志",
        "kind": "navigate",
        "risk": "low",
        "description": "重新读取日志流和检索结果。",
    },
    "filter-logs": {
        "label": "筛选日志",
        "kind": "navigate",
        "risk": "low",
        "description": "进入日志页面按服务、级别或时间筛选。",
    },
    "open-log-source": {
        "label": "打开日志来源",
        "kind": "navigate",
        "risk": "low",
        "description": "进入日志页面定位原始日志来源。",
    },
    "request-task-approval": {
        "label": "申请任务审批",
        "kind": "queue",
        "risk": "medium",
        "description": "在任务中心发起审批请求。",
    },
    "approve-task": {
        "label": "审批任务",
        "kind": "queue",
        "risk": "high",
        "description": "在任务中心完成受控任务审批。",
    },
    "pause-task": {
        "label": "暂停任务",
        "kind": "queue",
        "risk": "medium",
        "description": "在任务中心暂停正在处理的任务。",
    },
    "resume-task": {
        "label": "恢复任务",
        "kind": "queue",
        "risk": "medium",
        "description": "在任务中心恢复已暂停任务。",
    },
    "dispatch-task": {
        "label": "派发任务",
        "kind": "queue",
        "risk": "high",
        "description": "在任务中心将任务派发给受控执行器。",
    },
    "record-execution-evidence": {
        "label": "补执行证据",
        "kind": "queue",
        "risk": "medium",
        "description": "在任务中心登记命令、结果和日志证据。",
    },
    "complete-task": {
        "label": "完成任务",
        "kind": "queue",
        "risk": "medium",
        "description": "在任务中心完成任务并提交 closeout 证据。",
    },
    "open-task-source": {
        "label": "打开任务来源",
        "kind": "navigate",
        "risk": "low",
        "description": "进入任务来源页面查看上下文。",
    },
    "refresh-performance": {
        "label": "刷新性能指标",
        "kind": "navigate",
        "risk": "low",
        "description": "重新读取 CPU、内存、网络和系统性能。",
    },
    "select-time-range": {
        "label": "选择时间范围",
        "kind": "navigate",
        "risk": "low",
        "description": "进入性能页面调整指标时间范围。",
    },
    "execute-sandbox": {
        "label": "承接沙箱执行",
        "kind": "queue",
        "risk": "high",
        "description": "进入受控任务流程执行隔离验证。",
    },
    "copy-sandbox-code": {
        "label": "复制沙箱代码",
        "kind": "navigate",
        "risk": "low",
        "description": "进入沙箱页面复制待验证代码。",
    },
    "open-execution-log": {
        "label": "打开执行日志",
        "kind": "navigate",
        "risk": "low",
        "description": "进入日志页面查看沙箱执行证据。",
    },
    "create-quest": {
        "label": "创建积分任务",
        "kind": "queue",
        "risk": "medium",
        "description": "进入受控任务流程创建家庭积分任务。",
    },
    "complete-quest": {
        "label": "完成积分任务",
        "kind": "queue",
        "risk": "medium",
        "description": "进入受控任务流程完成积分任务并留证。",
    },
    "refresh-quests": {
        "label": "刷新积分任务",
        "kind": "navigate",
        "risk": "low",
        "description": "重新读取家庭积分任务和奖励状态。",
    },
    "register-instance": {
        "label": "登记控制面实例",
        "kind": "queue",
        "risk": "high",
        "description": "进入受控任务流程登记实例和路由。",
    },
    "copy-endpoint": {
        "label": "复制控制面地址",
        "kind": "navigate",
        "risk": "low",
        "description": "进入设置页面复制控制面 endpoint。",
    },
    "open-mesh": {
        "label": "打开网格设置",
        "kind": "navigate",
        "risk": "low",
        "description": "进入网格与 MCP 页面检查路由。",
    },
}


CAPABILITY_TO_PAGE = {
    "深度研究": "Research",
    "研究管线": "Research",
    "知识摄取与持久化": "Knowledge",
    "知识检索与推理": "Knowledge",
    "治理与合规": "C2G",
    "编排与执行": "Workflows",
    "算力与基础设施": "Compute",
    "通信与路由": "McpMesh",
    "协议与元模型": "Protocol",
    "自我与入口": "SystemMap",
}

# A capability domain can be surfaced by several pages.  The primary page
# above remains the canonical owner; these links describe legitimate secondary
# operator surfaces so cross-cutting pages are not reported as unmapped.
PAGE_CAPABILITY_LINKS: dict[str, tuple[str, ...]] = {
    "Home": ("capability-3", "capability-5", "capability-8"),
    "Guide": ("capability-8",),
    "DomainApps": ("capability-8",),
    "Overview": ("capability-5",),
    "Topology": ("capability-6",),
    "Research": ("capability-2",),
    "Knowledge": ("capability-1", "capability-2"),
    "GBrainAdmin": ("capability-1", "capability-2"),
    "Engines": ("capability-2", "capability-5"),
    "Assets": ("capability-4", "capability-7"),
    "Protocol": ("capability-4", "capability-7"),
    "Workflows": ("capability-4", "capability-7"),
    "C2G": ("capability-3",),
    "AlertCenter": ("capability-3",),
    "Debt": ("capability-3",),
    "L4Health": ("capability-8",),
    "Observability": ("capability-6", "capability-8"),
    "LogViewer": ("capability-8",),
    "TaskCenter": ("capability-3", "capability-4"),
    "Performance": ("capability-5",),
    "Sandbox": ("capability-4",),
    "QuestBoard": ("capability-8",),
    "Settings": ("capability-3", "capability-6"),
}


PROJECT_TO_PAGE = {
    "agora": "McpMesh",
    "kairon": "Engines",
    "gbrain": "Knowledge",
    "omo": "C2G",
    "metaos": "Workflows",
    "runtime": "Overview",
    "ecos": "Assets",
    "cockpit": "SystemMap",
    "cockpit-ui": "SystemMap",
    "l4-kernel": "L4Health",
    "model-driven": "Assets",
    "aetherforge": "Compute",
    "c2g": "C2G",
    "bus-foundation": "McpMesh",
    "omo-debt": "Debt",
    "observability": "Observability",
    "family-hub": "DomainApps",
    "toolbox": "Assets",
    "mesh-router": "Compute",
}

# Cross-cutting pages consume several project surfaces without owning a single
# project. Keep these links explicit so page maturity describes the real
# operating model instead of treating shared pages as unowned entry points.
PAGE_PROJECT_LINKS: dict[str, tuple[str, ...]] = {
    "Home": ("cockpit", "runtime", "omo", "observability"),
    "Guide": ("cockpit", "cockpit-ui"),
    "Topology": ("agora", "bus-foundation", "runtime", "observability"),
    "Compute": ("mesh-router", "aetherforge", "kairon"),
    "Research": ("gbrain", "kairon"),
    "GBrainAdmin": ("gbrain",),
    "Protocol": ("ecos", "model-driven", "metaos"),
    "Observability": ("observability", "runtime"),
    "AlertCenter": ("omo", "observability", "cockpit"),
    "LogViewer": ("runtime", "observability", "cockpit"),
    "Performance": ("runtime", "observability"),
    "Sandbox": ("ecos", "toolbox", "cockpit"),
    "QuestBoard": ("family-hub",),
    "Settings": ("agora", "cockpit", "cockpit-ui"),
    "TaskCenter": ("omo", "omo-debt", "c2g"),
}
