"""Cockpit usage paths and operating playbooks.

Split from api_system_map_catalog.py (god-module SRP, T6-10).
Pure data, no logic dependencies.
"""

from __future__ import annotations

from typing import Any

USAGE_PATHS: tuple[dict[str, Any], ...] = (
    {
        "id": "daily-ops",
        "title": "日常体检",
        "intent": "先看系统是否能用，再处理最紧急的问题。",
        "steps": ("Home", "AlertCenter", "TaskCenter", "LogViewer"),
    },
    {
        "id": "architecture-orientation",
        "title": "架构定位",
        "intent": "不知道某个项目归哪一层、该从哪进时使用。",
        "steps": ("Guide", "SystemMap", "McpMesh", "Assets", "Settings"),
    },
    {
        "id": "governance-loop",
        "title": "治理闭环",
        "intent": "把战略、任务、债务、证据和告警串成一条线。",
        "steps": ("C2G", "Workflows", "Debt", "Observability"),
    },
    {
        "id": "knowledge-work",
        "title": "知识工作",
        "intent": "从知识检索、引擎状态到技能资产逐步定位。",
        "steps": ("Knowledge", "GBrainAdmin", "Engines", "Assets", "McpMesh"),
    },
    {
        "id": "compute-routing",
        "title": "算力路由",
        "intent": "从算力节点和模型路由确认执行资源，再回到引擎或任务承接。",
        "steps": ("Compute", "McpMesh", "Engines", "TaskCenter"),
    },
    {
        "id": "research-publication",
        "title": "研究到发布",
        "intent": "从研究对象、知识上下文到发布和任务承接。",
        "steps": ("Research", "Knowledge", "TaskCenter", "C2G"),
    },
    {
        "id": "protocol-integrity",
        "title": "协议完整性",
        "intent": "确认协议定义、动作、后端和治理承接都具备证据。",
        "steps": ("Protocol", "Workflows", "Assets", "C2G"),
    },
    {
        "id": "domain-ops",
        "title": "领域作战",
        "intent": "进入家庭、OPC 等 L4 领域应用，同时守住 SSOT 边界。",
        "steps": ("DomainApps", "L4Health", "QuestBoard", "C2G"),
    },
    {
        "id": "runtime-diagnostics",
        "title": "运行诊断",
        "intent": "从服务状态、资源采样和拓扑证据定位运行问题。",
        "steps": ("Home", "Overview", "AlertCenter", "Performance", "Topology", "LogViewer"),
    },
    {
        "id": "safe-execution",
        "title": "安全执行",
        "intent": "先在隔离沙箱验证，再把结果带回任务或工作流。",
        "steps": ("Sandbox", "TaskCenter", "Workflows", "LogViewer"),
    },
    {
        "id": "control-plane-onboarding",
        "title": "控制面接入",
        "intent": "注册实例、确认路由和安全门，再挂载领域应用。",
        "steps": ("Settings", "McpMesh", "DomainApps", "Overview"),
    },
)


OPERATING_PLAYBOOKS: tuple[dict[str, Any], ...] = (
    {
        "id": "daily-health-check",
        "title": "每日 5 分钟体检",
        "goal": "先确认入口、告警、任务和日志是否正常，把当天最该处理的风险挑出来。",
        "frequency": "daily",
        "owner": "operator",
        "risk": "low",
        "steps": (
            {
                "id": "daily-home-scan",
                "page_id": "Home",
                "action": "查看健康摘要、趋势和首页快捷入口是否有异常。",
                "evidence": "首页健康卡片、运行项目数、待补能力数。",
                "done_when": "能说出当前最重要的一个系统状态变化。",
            },
            {
                "id": "daily-alert-triage",
                "page_id": "AlertCenter",
                "action": "按严重度扫一遍告警，确认是否有需要当天处理的 P0/P1。",
                "evidence": "告警中心的活动告警、规则状态和处置状态。",
                "done_when": "高风险告警已被确认、转任务或标记为无需动作。",
            },
            {
                "id": "daily-task-followup",
                "page_id": "TaskCenter",
                "action": "查看正在执行和阻塞的任务，决定今天推进哪三件事。",
                "evidence": "任务中心的进行中任务、阻塞任务和最近操作。",
                "done_when": "当天三件事有明确入口和下一步。",
            },
            {
                "id": "daily-log-check",
                "page_id": "LogViewer",
                "action": "只针对异常页面或服务看日志现场，避免无目标翻日志。",
                "evidence": "日志查看器里的错误片段、时间窗口和相关服务。",
                "done_when": "异常有证据位置；没有异常则结束巡检。",
            },
        ),
    },
    {
        "id": "compute-capacity-review",
        "title": "算力容量巡检",
        "goal": "确认模型路由、节点资源和成本状态一致，避免把调度问题误判成模型问题。",
        "frequency": "daily",
        "owner": "operator",
        "risk": "medium",
        "steps": (
            {
                "id": "compute-route-scan",
                "page_id": "Compute",
                "action": "检查当前模型路由、节点资源和成本采样，定位异常调度对象。",
                "evidence": "算力调配页的节点、路由、资源和成本状态。",
                "done_when": "目标路由和资源瓶颈有明确结论，或已进入任务中心继续处理。",
            },
        ),
    },
    {
        "id": "gbrain-control-plane-review",
        "title": "GBrain 控制面巡检",
        "goal": "核对智能体接入、访问凭证、模型校准和请求审计，确保智能能力可用且可追溯。",
        "frequency": "weekly",
        "owner": "knowledge",
        "risk": "high",
        "steps": (
            {
                "id": "gbrain-control-plane-scan",
                "page_id": "GBrainAdmin",
                "action": "检查智能体、凭证、模型校准和请求日志的当前状态与风险。",
                "evidence": "GBrain 管理页的接入状态、凭证安全门、校准结果和请求审计。",
                "done_when": "高风险配置已进入受控任务，或已明确记录无需动作的理由。",
            },
        ),
    },
    {
        "id": "weekly-governance-loop",
        "title": "每周治理闭环",
        "goal": "把战略、工作流、技术债和可观测证据串起来，避免治理停留在文档层。",
        "frequency": "weekly",
        "owner": "governance",
        "risk": "medium",
        "steps": (
            {
                "id": "weekly-strategy-review",
                "page_id": "C2G",
                "action": "检查战略意图、任务卡片和当前治理阶段是否一致。",
                "evidence": "C2G 战略中心的任务、决策和治理卡片。",
                "done_when": "本周目标能映射到具体任务或债务条目。",
            },
            {
                "id": "weekly-workflow-evidence",
                "page_id": "Workflows",
                "action": "查看 agent workflow 的最近执行、验证和 closeout 是否有断点。",
                "evidence": "工作流运行记录、verify 事件和 closeout 状态。",
                "done_when": "关键改动都有验证证据或明确补证计划。",
            },
            {
                "id": "weekly-debt-priority",
                "page_id": "Debt",
                "action": "按影响面和阻塞程度重排技术债优先级。",
                "evidence": "技术债务列表、评分和风险来源。",
                "done_when": "至少一个技术债进入本周可执行任务。",
            },
            {
                "id": "weekly-observability-check",
                "page_id": "Observability",
                "action": "核对关键服务是否有日志、指标和链路证据。",
                "evidence": "运行可观测页面的指标、日志和探针状态。",
                "done_when": "治理结论有运行证据支撑，而不是只靠口头判断。",
            },
        ),
    },
    {
        "id": "project-runtime-review",
        "title": "项目运行巡检",
        "goal": "从项目矩阵进入每个关键项目，确认目录、文档、命令、端口和验证是否闭环。",
        "frequency": "on-demand",
        "owner": "engineering",
        "risk": "medium",
        "steps": (
            {
                "id": "project-orientation-guide",
                "page_id": "Guide",
                "action": "先用站内导览确认当前问题属于哪条工作带和哪个入口。",
                "evidence": "导览页的页面分组、工作模式和推荐使用路径。",
                "done_when": "目标项目和问题已落到明确的 Cockpit 工作面。",
            },
            {
                "id": "project-map-filter",
                "page_id": "SystemMap",
                "action": "在项目矩阵里定位目标项目，看状态、运行、文档和命令列。",
                "evidence": "项目矩阵中的 operational、runtime、docs、commands。",
                "done_when": "目标项目的缺口和下一步清楚可见。",
            },
            {
                "id": "project-runtime-probe",
                "page_id": "Overview",
                "action": "对照运行大盘确认端口监听和服务状态是否一致。",
                "evidence": "端口注册表探针、运行项目数和服务节点状态。",
                "done_when": "能区分目录就绪、服务运行和验证通过三类状态。",
            },
            {
                "id": "project-workflow-proof",
                "page_id": "Workflows",
                "action": "查最近一次验证事件，确认它覆盖了目标项目改动面。",
                "evidence": "agent-workflow verify 事件和 claimed surfaces。",
                "done_when": "项目状态有最近验证证据，或明确标记为 unknown。",
            },
        ),
    },
    {
        "id": "domain-app-ops",
        "title": "领域应用作战",
        "goal": "把家庭、OPC、family-hub 等 L4 能力挂入 Cockpit，同时守住 SSOT 和安全边界。",
        "frequency": "weekly",
        "owner": "domain",
        "risk": "high",
        "steps": (
            {
                "id": "domain-contract-check",
                "page_id": "DomainApps",
                "action": "检查领域 app contract、SSOT 根、URL、验证命令和风险等级。",
                "evidence": "应用中心的 domain app contract 和能力边界。",
                "done_when": "知道每个领域应用是外部挂载、内置模块还是服务能力。",
            },
            {
                "id": "domain-health-check",
                "page_id": "L4Health",
                "action": "查看 L4 域健康，确认家庭、OPC 等领域是否有明显风险。",
                "evidence": "L4 健康趋势、风险提示和领域状态。",
                "done_when": "领域风险已转成任务、告警或本周行动。",
            },
            {
                "id": "domain-family-tasks",
                "page_id": "QuestBoard",
                "action": "把家庭任务、奖励或游戏化需求放在 family-hub 服务边界内处理。",
                "evidence": "积分冒险页、family-hub contract 和家庭任务入口。",
                "done_when": "家庭体验需求不和 Cockpit 平台职责混栈。",
            },
            {
                "id": "domain-governance-sync",
                "page_id": "C2G",
                "action": "把领域行动同步回治理任务，避免 app 成为新的信息孤岛。",
                "evidence": "C2G 任务、周回顾和治理卡片。",
                "done_when": "领域动作有治理归档位置和复盘入口。",
            },
        ),
    },
    {
        "id": "knowledge-work-session",
        "title": "知识工作会话",
        "goal": "从知识检索进入引擎、资产和 MCP 路由，找到资料并确认能力链路可用。",
        "frequency": "on-demand",
        "owner": "knowledge",
        "risk": "low",
        "steps": (
            {
                "id": "knowledge-query",
                "page_id": "Knowledge",
                "action": "先用知识中枢找资料、记忆或项目背景。",
                "evidence": "知识检索结果、记忆索引和相关来源。",
                "done_when": "目标问题有可引用的知识来源。",
            },
            {
                "id": "knowledge-engine-check",
                "page_id": "Engines",
                "action": "确认相关引擎是否可用，避免把检索失败误判成资料不存在。",
                "evidence": "引擎调度页的 Kairon/GBrain/KOS 状态。",
                "done_when": "检索链路的引擎状态已确认。",
            },
            {
                "id": "knowledge-asset-route",
                "page_id": "Assets",
                "action": "查看是否已有技能、工具或自动化能直接处理该问题。",
                "evidence": "技术资产库中的技能、工具管线和 workflow。",
                "done_when": "找到可复用能力，或明确需要补新能力。",
            },
            {
                "id": "knowledge-route-debug",
                "page_id": "McpMesh",
                "action": "如果能力不可达，回到 MCP 网格检查路由和 BOS URI。",
                "evidence": "MCP 实例、BOS URI 和路由解析状态。",
                "done_when": "能力不可达有路由层证据，能进入修复流程。",
            },
        ),
    },
    {
        "id": "research-publication-loop",
        "title": "研究到发布闭环",
        "goal": "把研究对象从问题、证据和追问推进到发布与任务承接。",
        "frequency": "weekly",
        "owner": "knowledge",
        "risk": "medium",
        "steps": (
            {
                "id": "research-object-review",
                "page_id": "Research",
                "action": "确认研究对象、来源、追问和最近事件。",
                "evidence": "研究对象详情、时间线和 dossier。",
                "done_when": "研究结论和下一步问题清楚。",
            },
            {
                "id": "research-knowledge-context",
                "page_id": "Knowledge",
                "action": "补充知识来源和长期上下文。",
                "evidence": "检索结果、来源定位和记忆记录。",
                "done_when": "发布内容有可引用上下文。",
            },
            {
                "id": "research-task-handoff",
                "page_id": "TaskCenter",
                "action": "把研究后的动作沉到任务或草稿。",
                "evidence": "任务来源、负责人和状态。",
                "done_when": "发布后的动作有追踪入口。",
            },
            {
                "id": "research-governance-sync",
                "page_id": "C2G",
                "action": "将高影响研究结论带回战略和治理语境。",
                "evidence": "C2G 卡片、决策或周回顾记录。",
                "done_when": "研究影响进入治理闭环。",
            },
        ),
    },
    {
        "id": "protocol-integrity-loop",
        "title": "协议层完整性检查",
        "goal": "巡检工作流定义、动作、后端、运行证据和治理承接。",
        "frequency": "weekly",
        "owner": "protocol",
        "risk": "medium",
        "steps": (
            {
                "id": "protocol-registry-review",
                "page_id": "Protocol",
                "action": "查看协议工作台中的工作流、动作和后端注册数量。",
                "evidence": "协议层汇总和最近运行记录。",
                "done_when": "定义层、动作层和后端层的状态可解释。",
            },
            {
                "id": "protocol-workflow-proof",
                "page_id": "Workflows",
                "action": "确认工作流运行、审批和失败记录。",
                "evidence": "MetaOS 工作流运行证据。",
                "done_when": "关键协议动作有最近运行或验证证据。",
            },
            {
                "id": "protocol-asset-link",
                "page_id": "Assets",
                "action": "回到技术资产确认定义和实现来源。",
                "evidence": "技能、管线和工作流资产。",
                "done_when": "协议问题能回跳到具体资产。",
            },
            {
                "id": "protocol-governance-handoff",
                "page_id": "C2G",
                "action": "把协议缺口沉到治理任务或路线图。",
                "evidence": "C2G 任务、路线图和验收条件。",
                "done_when": "协议缺口有 owner、优先级和验收口径。",
            },
        ),
    },
    {
        "id": "control-plane-onboarding-loop",
        "title": "控制面接入闭环",
        "goal": "注册新实例后，依次确认路由、领域挂载和运行探针，避免只写入配置不验证链路。",
        "frequency": "on-demand",
        "owner": "operator",
        "risk": "medium",
        "steps": (
            {
                "id": "control-plane-register",
                "page_id": "Settings",
                "action": "登记实例服务名和 MCP 接入点。",
                "evidence": "注册响应、实例地址和控制面状态。",
                "done_when": "实例注册结果明确且没有把 token 写入页面或日志。",
            },
            {
                "id": "control-plane-route-check",
                "page_id": "McpMesh",
                "action": "确认实例进入网格并能解析路由。",
                "evidence": "MCP 实例、BOS URI 和路由探针。",
                "done_when": "新实例有可验证的路由证据。",
            },
            {
                "id": "control-plane-domain-check",
                "page_id": "DomainApps",
                "action": "涉及领域应用时，检查 contract、SSOT 和安全门。",
                "evidence": "应用中心的 contract、健康和安全检查。",
                "done_when": "领域边界和写入风险明确。",
            },
            {
                "id": "control-plane-runtime-check",
                "page_id": "Overview",
                "action": "用真实运行探针确认实例状态。",
                "evidence": "服务状态、端口监听和健康结果。",
                "done_when": "配置、路由和运行三层状态一致。",
            },
        ),
    },
    {
        "id": "runtime-diagnostic-loop",
        "title": "运行诊断闭环",
        "goal": "从真实探针确认运行状态，用资源、拓扑和日志逐步缩小问题范围。",
        "frequency": "on-demand",
        "owner": "operator",
        "risk": "low",
        "steps": (
            {
                "id": "runtime-overview",
                "page_id": "Overview",
                "action": "确认服务节点和运行探针是否有异常。",
                "evidence": "服务状态、端口监听和健康状态。",
                "done_when": "问题范围缩小到具体服务或明确无运行异常。",
            },
            {
                "id": "runtime-alert-triage",
                "page_id": "AlertCenter",
                "action": "确认严重告警、处置状态和是否需要承接任务。",
                "evidence": "活动告警、规则状态、确认/静默/解决记录和任务入口。",
                "done_when": "告警已明确处置，或已有可追踪的后续任务。",
            },
            {
                "id": "runtime-performance",
                "page_id": "Performance",
                "action": "查看真实 CPU、内存、磁盘和网络采样。",
                "evidence": "psutil 实时采样和服务资源可用性。",
                "done_when": "确认资源瓶颈存在或排除资源因素。",
            },
            {
                "id": "runtime-topology",
                "page_id": "Topology",
                "action": "只依据显式依赖关系检查服务拓扑，不把推断连线当证据。",
                "evidence": "运行节点和服务声明的依赖边。",
                "done_when": "调用关系有来源，或明确缺少关系证据。",
            },
            {
                "id": "runtime-log-context",
                "page_id": "LogViewer",
                "action": "在明确时间窗口和服务范围内查看日志现场。",
                "evidence": "日志片段、时间窗口和服务过滤条件。",
                "done_when": "异常有可回跳的日志证据。",
            },
        ),
    },
    {
        "id": "safe-execution-loop",
        "title": "安全执行闭环",
        "goal": "用隔离实验降低执行风险，再把可复现结果沉到正式任务和工作流。",
        "frequency": "on-demand",
        "owner": "engineering",
        "risk": "medium",
        "steps": (
            {
                "id": "sandbox-experiment",
                "page_id": "Sandbox",
                "action": "在隔离环境执行最小复现片段。",
                "evidence": "沙箱代码、标准输出和执行结果。",
                "done_when": "实验结果可复现且未越过安全门。",
            },
            {
                "id": "sandbox-task-handoff",
                "page_id": "TaskCenter",
                "action": "把下一步沉到正式任务或只读草稿。",
                "evidence": "任务状态、来源和操作证据。",
                "done_when": "后续动作有负责人和可追踪入口。",
            },
            {
                "id": "sandbox-workflow-check",
                "page_id": "Workflows",
                "action": "需要重复执行时，检查是否已有受控工作流。",
                "evidence": "工作流定义、审批节点和最近运行记录。",
                "done_when": "确认复用现有工作流或提出补能力项。",
            },
        ),
    },
)
