#!/usr/bin/env python3
"""KOS init — interactive workspace setup wizard.

Generates a workspace-config.py + workspace-manifest.json pair,
auto-discovers domains, and triggers first index.

Usage:
    kos init              # Interactive wizard
    kos init --dry-run    # Preview what would be created
    kos init --force      # Overwrite existing config
"""

import argparse
import json
import os
import sys
from datetime import datetime
from pathlib import Path
from typing import Any

WORKSPACE_CONFIG_PY = '''#!/usr/bin/env python3
"""Auto-generated workspace config for KOS.

Generated by `kos init` on {generated_at}.
Edit workspace-manifest.json to customize zones, domains, and indexing.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Any

TOOLS_DIR = Path(__file__).resolve().parent
DOCUMENTS_ROOT = Path("{documents_root}")
MANIFEST_PATH = TOOLS_DIR / "workspace-manifest.json"


class WorkspaceConfigError(RuntimeError):
    """Raised when workspace registry files are missing or invalid."""


    def _load_json(path: Path) -> dict[str, Any]:
        if not path.exists():
            raise WorkspaceConfigError(f"Registry file does not exist: {{path}}")
        with path.open("r", encoding="utf-8") as handle:
            return json.load(handle)


@lru_cache(maxsize=1)
def get_workspace_manifest() -> dict[str, Any]:
    return _load_json(MANIFEST_PATH)


def get_documents_root() -> Path:
    return DOCUMENTS_ROOT


def get_zone(zone_id: str) -> dict[str, Any]:
    zones = get_workspace_manifest().get("zones", {{}})
    try:
        return zones[zone_id]
    except KeyError as exc:
        raise WorkspaceConfigError(f"Unknown workspace zone: {{zone_id}}") from exc


def get_zone_path(zone_id: str) -> Path:
    zone = get_zone(zone_id)
    if zone.get("scope") == "external" and "absolutePath" in zone:
        return Path(zone["absolutePath"]).resolve()
    if "relativePath" in zone:
        return (DOCUMENTS_ROOT / zone["relativePath"]).resolve()
    if "absolutePath" in zone:
        return Path(zone["absolutePath"]).resolve()
    raise WorkspaceConfigError(
        f"Zone {{zone_id}} has neither relativePath nor absolutePath"
    )


def get_artifact_path(artifact_id: str) -> Path:
    artifacts = get_workspace_manifest().get("artifacts", {{}})
    try:
        artifact = artifacts[artifact_id]
    except KeyError as exc:
        raise WorkspaceConfigError(f"Unknown artifact id: {{artifact_id}}") from exc
    base_path = get_zone_path(artifact["relativeToZone"])
    return (base_path / artifact["relativePath"]).resolve()

''

'''

MANIFEST_TEMPLATE = {
    "version": "2.5",
    "description": "KOS workspace manifest (auto-generated)",
    "documentsRoot": ".",
    "primaryVaultZone": "default",
    "groups": {},
    "zoneRoles": {
        "source": {"label": "Knowledge Source", "writePolicy": "readonly", "description": "正式知识内容，Agent 只读"},
        "capture": {"label": "采集入口", "writePolicy": "full", "description": "临时/采集内容，Agent 可读写"},
        "archive": {"label": "归档", "writePolicy": "readonly", "description": "历史版本，不参与检索"},
        "support": {"label": "系统基础设施", "writePolicy": "managed", "description": "工具/配置/脚本"},
    },
    "zones": {},
    "domains": {},
    "safeWriteZones": [],
    "pathAliases": {},
    "artifacts": {
        "retrievalDatabase": {"relativeToZone": "default", "relativePath": ".kos/index.sqlite"},
        "qualityHistory": {"relativeToZone": "default", "relativePath": ".kos/quality_history.jsonl"},
    },
    "indexing": {
        "excludePrefixes": [
            ".git",
            ".obsidian",
            ".claude",
            ".venv",
            ".omc",
            ".pytest_cache",
            "__pycache__",
            "node_modules",
            "docker",
        ],
        "archiveIndexPolicy": "separate_corpus",
        "externalDomainIndexPolicy": "format-aware",
        "searchDefaultExclude": [],
        "indexingStrategies": {},
    },
    "entitySources": [],
    "predicatePatterns": {
        "zh": {
            "reports_to": ["下属→上级", "汇报给", "向.*汇报", "直属上级"],
            "manages": ["上级→下属", "直接下属", "分管"],
            "coordinates": ["协调角色", "跨组协调", "对接", "协同"],
            "invites_to": ["点名.*参会", "邀请", "让.*参加"],
            "liaises_with": ["联络员", "联系人"],
            "owns": ["\\bowner\\b", "主导", "承建", "项目owner"],
            "works_on": ["参与", "主要成员", "借调人员"],
            "member_of": ["同组", "成员", "组员"],
        },
        "en": {
            "reports_to": ["reports to", "directly under", "subordinate"],
            "manages": ["manages", "supervises", "oversees"],
            "coordinates": ["coordinates with", "liaises with", "works with"],
            "invites_to": ["invites", "asks to join"],
            "liaises_with": ["contact for", "point of contact", "liaison"],
            "owns": ["\\bowner\\b", "owns", "responsible for"],
            "works_on": ["works on", "contributor to", "participates in"],
            "member_of": ["member of", "part of", "belongs to"],
        },
    },
}


def _ask(prompt: str, default: str = "") -> str:
    """Ask user for input with optional default."""
    if default:
        full = f"{prompt} [{default}]: "
    else:
        full = f"{prompt}: "
    try:
        val = input(full).strip()
    except (EOFError, KeyboardInterrupt):
        print("\n❌ Aborted.")
        sys.exit(1)
    return val if val else default


def _ask_yes_no(prompt: str, default: bool = False) -> bool:
    """Ask a yes/no question."""
    suffix = " [Y/n]: " if default else " [y/N]: "
    try:
        val = input(prompt + suffix).strip().lower()
    except (EOFError, KeyboardInterrupt):
        print("\n❌ Aborted.")
        sys.exit(1)
    if not val:
        return default
    return val in ("y", "yes")


def _discover_zones(root: Path) -> tuple[dict, dict, dict, list]:
    """Scan root for subdirectories and propose zones + domains."""
    zones = {}
    domains = {}
    strategies = {}
    group_zones = []
    zone_idx = 0
    candidates = [root]
    for extra in [Path.home() / "Documents", Path.home() / "Desktop"]:
        if extra != root and extra.exists():
            candidates.append(extra)
    seen_paths = set()
    for base in candidates:
        if not base.exists():
            continue
        for sub in sorted(base.iterdir()):
            if not sub.is_dir() or sub.name.startswith("."):
                continue
            abs_path = str(sub.resolve())
            if abs_path in seen_paths:
                continue
            seen_paths.add(abs_path)
            zone_id = f"zone-{zone_idx}"
            zone_idx += 1
            zones[zone_id] = {
                "label": sub.name,
                "role": "source",
                "absolutePath": abs_path,
                "authoritative": True,
                "indexable": True,
                "defaultWritePolicy": "readonly",
                "scope": "external",
            }
            domains[zone_id] = {"zoneId": zone_id, "description": sub.name}
            group_zones.append(zone_id)
            strategies[zone_id] = _scan_indexing_strategy(sub)
    return zones, domains, strategies, group_zones


def _scan_indexing_strategy(folder: Path, max_depth: int = 2) -> dict:
    """Scan folder structure to guess indexing strategies."""
    strategies = {}
    counts = {"md": 0, "txt": 0, "docx": 0, "pdf": 0, "xlsx": 0, "other": 0}
    try:
        for item in folder.iterdir():
            if not item.is_dir() or item.name.startswith("."):
                if item.is_file():
                    ext = item.suffix.lower()
                    if ext in counts:
                        counts[ext.lstrip(".")] += 1
                    else:
                        counts["other"] += 1
                continue
            subdir_name = item.name
            sub_counts = {"md": 0, "txt": 0, "docx": 0, "pdf": 0, "xlsx": 0, "other": 0}
            try:
                for f in item.iterdir():
                    if not f.is_file():
                        continue
                    ext = f.suffix.lower().lstrip(".")
                    if ext in sub_counts:
                        sub_counts[ext] += 1
                    else:
                        sub_counts["other"] += 1
                    if sum(sub_counts.values()) >= 20:
                        break
            except PermissionError:
                pass
            total = sum(sub_counts.values())
            if total == 0:
                strategies[subdir_name] = "filename_only"
                continue
            text_like = sub_counts["md"] + sub_counts["txt"] + sub_counts["docx"] + sub_counts["pdf"]
            strategies[subdir_name] = "full_text" if text_like / total >= 0.5 else "filename_only"
    except PermissionError:
        pass
    if not strategies:
        total = sum(counts.values())
        if total > 0:
            text_like = counts["md"] + counts["txt"] + counts["docx"] + counts["pdf"]
            strategies["default"] = "full_text" if text_like / total >= 0.5 else "filename_only"
        else:
            strategies["default"] = "full_text"
    strategies["default"] = strategies.get("default", "full_text")
    return strategies


def _generate_manifest(root: Path, zones: dict, domains: dict, strategies: dict, group_zones: list) -> dict[str, Any]:
    """Build a complete manifest from discovered data."""
    manifest: dict[str, Any] = dict(MANIFEST_TEMPLATE)
    manifest["zones"] = zones
    manifest["domains"] = domains
    manifest["groups"] = {"default": {"label": "All", "zones": group_zones}}
    manifest["indexing"]["indexingStrategies"] = strategies
    manifest["documentsRoot"] = str(root)
    if zones:
        manifest["primaryVaultZone"] = list(zones.keys())[0]
        first_zone = list(zones.keys())[0]
        manifest["artifacts"]["retrievalDatabase"]["relativeToZone"] = first_zone
        manifest["artifacts"]["retrievalDatabase"]["relativePath"] = ".kos/index.sqlite"
        manifest["artifacts"]["qualityHistory"]["relativeToZone"] = first_zone
        manifest["artifacts"]["qualityHistory"]["relativePath"] = ".kos/quality_history.jsonl"
    return manifest


def main() -> None:
    parser = argparse.ArgumentParser(description="KOS workspace init wizard")
    parser.add_argument("--dry-run", action="store_true", help="Preview only, don't write files")
    parser.add_argument("--force", action="store_true", help="Overwrite existing config")
    parser.add_argument("--root", type=str, default="", help="Workspace root directory")
    args = parser.parse_args()

    print("🚀 KOS Init — Knowledge Operating System Setup\n")
    interactive = sys.stdin.isatty() and not args.root and not args.dry_run

    default_root = str(Path.home() / "Documents")
    if args.root:
        root = Path(args.root).expanduser().resolve()
    else:
        root_input = _ask("Workspace root directory", default_root)
        root = Path(root_input).expanduser().resolve()

    if not root.exists():
        if interactive:
            if _ask_yes_no(f"Directory does not exist: {root}\nCreate it?", default=True):
                root.mkdir(parents=True, exist_ok=True)
            else:
                print("❌ Aborted.")
                sys.exit(1)
        else:
            root.mkdir(parents=True, exist_ok=True)
            print(f"   Created directory: {root}")

    default_out = str(Path.home() / ".kos")
    if interactive:
        out_input = _ask("Where to save KOS config", default_out)
        out_dir = Path(out_input).expanduser().resolve()
    else:
        out_dir = Path(default_out).expanduser().resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    config_py_path = out_dir / "workspace_config.py"
    manifest_path = out_dir / "workspace-manifest.json"

    if (config_py_path.exists() or manifest_path.exists()) and not args.force:
        if interactive:
            if not _ask_yes_no(f"Config already exists in {out_dir}. Overwrite?", default=False):
                print("❌ Aborted.")
                sys.exit(1)
        else:
            pass

    print(f"\n🔍 Scanning {root} …")
    zones, domains, strategies, group_zones = _discover_zones(root)

    if not zones:
        print("⚠️  No subdirectories found. Creating a single default zone.")
        zones["default"] = {
            "label": "Default",
            "role": "source",
            "absolutePath": str(root),
            "authoritative": True,
            "indexable": True,
            "defaultWritePolicy": "readonly",
            "scope": "external",
        }
        domains["default"] = {"zoneId": "default", "description": "Default workspace"}
        group_zones = ["default"]
        strategies["default"] = {"default": "full_text"}

    print(f"   Discovered {len(zones)} zone(s):")
    for zid, zinfo in zones.items():
        print(f"      • {zid}: {zinfo['label']}")

    if interactive:
        print("\n📝 Review zones (press Enter to keep all):")
        to_remove = []
        for zid in list(zones.keys()):
            label = zones[zid]["label"]
            keep = _ask_yes_no(f"   Include '{label}'?", default=True)
            if not keep:
                to_remove.append(zid)
        for zid in to_remove:
            del zones[zid]
            del domains[zid]
            del strategies[zid]
            group_zones.remove(zid)
        if not zones:
            print("❌ No zones selected. Aborting.")
            sys.exit(1)

    manifest = _generate_manifest(root, zones, domains, strategies, group_zones)

    if args.dry_run:
        print("\n📋 Dry-run preview:")
        print(f"   Config dir: {out_dir}")
        print(f"   Zones: {len(zones)}")
        print("   Manifest preview (first 40 lines):")
        preview = json.dumps(manifest, indent=2, ensure_ascii=False).splitlines()[:40]
        for line in preview:
            print(f"   {line}")
        print("\n✅ Dry-run complete. Run without --dry-run to create files.")
        sys.exit(0)

    config_content = WORKSPACE_CONFIG_PY.format(
        generated_at=datetime.now().isoformat(),
        documents_root=str(root),
    )
    with open(config_py_path, "w", encoding="utf-8") as f:
        f.write(config_content)
    with open(manifest_path, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2, ensure_ascii=False)

    print(f"\n✅ Created config in {out_dir}")
    print(f"   • {config_py_path.name}")
    print(f"   • {manifest_path.name}")
    print(f"   • {len(zones)} zone(s), {len(domains)} domain(s)")

    print("\n📌 Next steps:")
    print("   1. Export KOS_HOME:")
    print(f"      export KOS_HOME={out_dir}")
    print(f"      echo 'export KOS_HOME={out_dir}' >> ~/.zshrc")
    print("   2. Verify:")
    print("      kos status")
    print("   3. Build index:")
    print("      kos index --all")

    if interactive and _ask_yes_no("\nRun first index now?", default=True):
        print("\n🔨 Running first index …")
        env = os.environ.copy()
        env["KOS_HOME"] = str(out_dir)
        import subprocess as sp

        indexer = Path(__file__).resolve().parent / "kos-indexer.py"
        if indexer.exists():
            r = sp.run([sys.executable, str(indexer), "index"], capture_output=True, text=True, env=env, timeout=300)
            print(r.stdout)
            if r.returncode != 0:
                print(f"⚠️  Indexer exited with code {r.returncode}")
                if r.stderr:
                    print(r.stderr[:500])
        else:
            print("⚠️  kos-indexer.py not found. Skipping auto-index.")

    print("\n🎉 KOS workspace ready!")


if __name__ == "__main__":
    main()
