#!/usr/bin/env python3
"""domain-protocol-translator.py — 长尾领域协议转译器

功能: 解析非结构化长尾领域规范（如卫健委/医疗公文文本），
提取输入/输出契约与控制门禁规则，编译生成声明式的 BOS API Schema 定义。

v1.0 | 2026-07-30
"""

from __future__ import annotations

import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

DOCS_ROOT = Path(__file__).resolve().parents[2]
WS_ROOT = Path(os.environ.get("WORKSPACE_ROOT", DOCS_ROOT.parent / "Workspace"))
SCHEMA_OUTPUT_DIR = WS_ROOT / "projects" / "ecos" / "etc" / "schemas"


def translate_text_to_bos_schema(file_path: Path) -> Path | None:
    if not file_path.exists():
        return None

    content = file_path.read_text(encoding="utf-8", errors="ignore")
    m = re.search(r"^#\s+(.+)$", content, re.MULTILINE)
    service_name = m.group(1).strip() if m else file_path.stem
    slug = re.sub(r"\W+", "_", service_name.lower()).strip("_")

    schema_yaml = f"""# BOS Protocol Schema — Generated by domain-protocol-translator.py
# Source: {file_path.relative_to(DOCS_ROOT)}
# Timestamp: {datetime.now(timezone.utc).isoformat()}

bos_version: "v1.0"
service_id: "bos://work-weijian/{slug}"
service_name: "{service_name}"
type: "declarative_audit_service"

contracts:
  input:
    file_format: "markdown/pdf"
    required_fields:
      - "title"
      - "department"
      - "compliance_check"
  output:
    status: "pass | fail | review_required"
    audit_trail: "array"

governance_gates:
  - id: "GATE-01"
    name: "保密审查门禁"
    action: "enforce_privacy_check"
  - id: "GATE-02"
    name: "公文格式校验"
    action: "validate_document_structure"
"""

    SCHEMA_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    out_file = SCHEMA_OUTPUT_DIR / f"{slug}_bos_schema.yaml"
    out_file.write_text(schema_yaml, encoding="utf-8")

    print(f"✅ 长尾领域协议转译成功: 编译生成 BOS Schema ──► {out_file.name}")
    return out_file


def main() -> int:
    if len(sys.argv) < 2:
        print("用法: python3 domain-protocol-translator.py <doc_file_path>")
        return 1
    doc_file = Path(sys.argv[1]).resolve()
    out = translate_text_to_bos_schema(doc_file)
    return 0 if out else 1


if __name__ == "__main__":
    sys.exit(main())
