"""SSOT integration — connector state/entity management via SSOT domains.

Each connector maps to an SSOT domain directory under ~/.iris/domains/{name}/.
- domain.yaml: connector metadata
- entities.yaml: platform objects (notebooks, books, columns)
- facts.yaml: sync status, counts, timestamps
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from iris.config import IrisConfig


class SSOTDomainAdapter:
    """Manage connector state as SSOT domains.

    Creates/reads/updates YAML files in the SSOT domain format.
    When ssot-kernel is available, uses load_domain() for typed access.
    """

    DOMAIN_YAML_TEMPLATE = """# SSOT Domain: {name}
# Auto-generated by iris connector hub
domain:
  name: "{name}"
  display_name: "{display_name}"
  version: "0.1.0"
  description: "Connector state for {display_name}"
"""

    ENTITIES_YAML_TEMPLATE = """# Entities: {name}
# Auto-generated by iris connector hub
entities:
  - id: "{name}/platform"
    name: "{display_name}"
    meta_type: DOMAIN
    entity_type: "platform"
    status: "active"
    attributes: {{}}
"""

    FACTS_YAML_TEMPLATE = """# Facts: {name}
# Auto-generated by iris connector hub
facts:
  - id: "{name}/initialized"
    title: "Connector initialized"
    value: "true"
    source: "iris"
"""

    @staticmethod
    def _safe_yaml_string(value: str) -> str:
        """Escape string for safe embedding in YAML double-quoted value."""
        return value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")

    def __init__(self, config: IrisConfig | None = None):
        self._config = config or IrisConfig()
        self._ssot_available = self._check_ssot()

    def _check_ssot(self) -> bool:
        try:
            import ssot_kernel  # type: ignore[reportMissingImports]

            return True
        except ImportError:
            return False

    @property
    def domains_dir(self) -> Path:
        return self._config.domains_dir

    def ensure_domain(self, name: str, display_name: str = "") -> Path:
        """Create SSOT domain directory and YAML files if they don't exist."""
        if not re.match(r"^[a-zA-Z0-9_-]+$", name):
            raise ValueError(f"Invalid domain name: {name!r}")

        domain_dir = self.domains_dir / name
        domain_dir.mkdir(parents=True, exist_ok=True)

        if not display_name:
            display_name = name.title()

        safe_name = self._safe_yaml_string(name)
        safe_display = self._safe_yaml_string(display_name)

        files = {
            domain_dir / "domain.yaml": self.DOMAIN_YAML_TEMPLATE.format(name=safe_name, display_name=safe_display),
            domain_dir / "entities.yaml": self.ENTITIES_YAML_TEMPLATE.format(name=safe_name, display_name=safe_display),
            domain_dir / "facts.yaml": self.FACTS_YAML_TEMPLATE.format(name=safe_name, display_name=safe_display),
        }

        for path, content in files.items():
            if not path.exists():
                path.write_text(content)

        return domain_dir

    def load_domain(self, name: str) -> dict[str, Any] | None:
        """Load SSOT domain using ssot-kernel if available."""
        domain_dir = self.domains_dir / name
        if not domain_dir.exists():
            return None

        if not self._ssot_available:
            return {
                "domain_dir": str(domain_dir),
                "note": "ssot-kernel not installed — structured loading unavailable",
            }

        try:
            from ssot_kernel.config_loader import load_domain  # type: ignore[reportMissingImports]

            config = load_domain(str(domain_dir))
            return {
                "domain_dir": str(domain_dir),
                "entities": [{"id": e.id, "name": e.name, "meta_type": e.meta_type.value} for e in config.entities],
                "facts": [{"id": f.id, "title": f.title, "value": f.value} for f in config.facts],
            }
        except Exception as e:
            return {"domain_dir": str(domain_dir), "error": str(e)}

    def domain_exists(self, name: str) -> bool:
        return (self.domains_dir / name).exists()

    def list_domains(self) -> list[str]:
        if not self.domains_dir.exists():
            return []
        return sorted(d.name for d in self.domains_dir.iterdir() if d.is_dir())

    def is_ssot_available(self) -> bool:
        return self._ssot_available

    def status(self) -> dict[str, Any]:
        domains_data: dict[str, Any] = {}
        if self.domains_dir.exists():
            for domain_name in self.list_domains():
                domains_data[domain_name] = self.load_domain(domain_name)

        return {
            "ssot_available": self._ssot_available,
            "domains_dir": str(self.domains_dir),
            "domains": self.list_domains(),
            "domain_data": domains_data,
        }
