"""Forge — 统一工具注册、发现与治理层"""

from forge.design_asset_adapter import (
    build_design_context,
    build_design_prompt,
    choose_design_assets,
    match_assets,
    scan_design_assets,
    write_manifest,
)
from forge.forge import (  # type: ignore[import-not-found]
    ALIASES,
    COMMANDS,
    SCRIPTS,
    SRC,
    TOOLBOX,
    VERIFY_COMMANDS,
    cmd_capture,
    cmd_dashboard,
    cmd_design_assets,
    cmd_health,
    cmd_help,
    cmd_install,
    cmd_routine,
    cmd_schedule,
    cmd_sniff,
    cmd_status,
    cmd_verify,
    main,
)

__all__ = (
    "ALIASES",
    "COMMANDS",
    "SCRIPTS",
    "SRC",
    "TOOLBOX",
    "VERIFY_COMMANDS",
    "build_design_context",
    "build_design_prompt",
    "choose_design_assets",
    "match_assets",
    "scan_design_assets",
    "write_manifest",
    "cmd_capture",
    "cmd_dashboard",
    "cmd_design_assets",
    "cmd_health",
    "cmd_help",
    "cmd_install",
    "cmd_routine",
    "cmd_schedule",
    "cmd_sniff",
    "cmd_status",
    "cmd_verify",
    "main",
)
